### PR TITLE
Fix some minor build stuff

### PR DESCRIPTION
**Pull request by QuLogic**
In a6b58f42, the aux directory for autotools stuff was changed to `script`, but some things (like ignore files) were not updated to this new path.

Secondly, make undefined symbols an error, since it's necessary for Windows anyway. This should make inconsistent failures like in #800 stop occurring (because all builds would fail). I'm not sure if this argument is supported everywhere, so I guess we'll see what happens with the CI...

### CODE REVIEW

**Comment by QuLogic** [comment]
Hmm, no AppVeyor? That's really what I was interested in...

**Comment by am11** [comment]
For some reason, Appveyor is not picking up the webhook. @xzyfer updated the webhook URL in settings.

@FeodorFitsner, can you please tell us besides updating the webhook URL, what else do we need to change to hear back from https://ci.appveyor.com/project/sass/libsass?

**Comment by FeodorFitsner** [comment]
1) make sure webhook URL is from right project 2) have at least "push" and "pull_request" events ticked on webhook settings

3) check "Recent deliveries" for any non-OK results


-Feodor

**Comment by am11** [comment]
@xzyfer, @mgreter, can you please confirm what @FeodorFitsner's has pointed out?

You can find those settings under Appveyor Web Hook settings page on GitHub:

(something like https://github.com/sass/libsass/settings/hooks/ `<some-hook-id>`)

It looks like:

webhook-settings

**Comment by xzyfer** [comment]
I spent about an hour looking into this. Our setup is exactly the same as node-sass. AppVeyor is pickup the builds, it's just not update the build status. I think issue may be on GH's end... maybe? i dunno

**Comment by xzyfer** [comment]
screen shot 2015-01-06 at 12 06 16 pm

**Comment by xzyfer** [comment]
FWIW @QuLogic this appears to have passed in AppVeyor https://ci.appveyor.com/project/sass/libsass/build/1.0.57

**Comment by am11** [comment]
Thanks @xzyfer!
@FeodorFitsner, previously the hook was tied to @hcatlin's account: https://github.com/hcatlin/libsass. We updated it to point to https://github.com/sass/libsass when this problem started. Is there any other tip you can provide to *relax* this situation? :)

**Comment by mgreter** [comment]
FYI: I have activated "status" recently in the hope it might solve this ... beside that I have no idea. @xzyfer do you have admin access at appveyor for that repository? Maybe we need some setting there?

**Comment by FeodorFitsner** [comment]
Could you paste a screenshot of webhook settings from GitHub?

-Feodor

**Comment by am11** [comment]
@mgreter, you and @xzyfer both are admins. :)

**Comment by am11** [comment]
@mgreter, you and @xzyfer both are admins. :)

@FeodorFitsner, its right here: https://github.com/sass/libsass/pull/805#issuecomment-68811040

**Comment by xzyfer** [comment]
FYI: I confirmed our settings are the same as node-sass in both GH and AppVeyor yesterday.

**Comment by xzyfer** [comment]
@mgreter you'll need to log out of AppVeyor and re-login then select `sass` from the dropdown that appears.

**Comment by FeodorFitsner** [comment]
OK, and what's correspondent project at AppVeyor?

-Feodor

**Comment by xzyfer** [comment]
https://ci.appveyor.com/project/sass/libsass/settings

screen shot 2015-01-06 at 12 42 25 pm

**Comment by FeodorFitsner** [comment]
I see queued builds: https://ci.appveyor.com/project/sass/libsass/history Seems to be OK?

**Comment by mgreter** [comment]
@FeodorFitsner The issue is that "CI reports" are not included. As you can see in https://github.com/sass/libsass/pull/811, only Travis-CI reports it's status to the PR.

**Comment by FeodorFitsner** [comment]
Will take a look.

-Feodor

**Comment by QuLogic** [comment]
Since @xzyfer mentioned that this passed on AppVeyor, I guess we can merge this, the missing CI results notwithstanding.

**Comment by am11** [comment]
Following https://github.com/appveyor/ci/issues/157, I had a brief email conversation with @FeodorFitsner and GitHub staff, I have found the solution for AppVeyor hook problem.

Currently, if the owner logon to AppVeyor, select Sass account and browse to https://ci.appveyor.com/account, they will see my account as GitHub authorization. It was set to Andrew's account, I revoked and re-authorize with my account to test whether it keeps the history, which it does.

The issue is neither Andrew nor me are owners of LibSass, but only node-sass. So the solution is simple; either @xzyfer, @mgreter or anyone with Owner role for both node-sass and libsass can logon to https://ci.appveyor.com/account with GitHub creds, select Sass account and click the revoke button under GitHub account then click authorize. This will hook both repos.

**Comment by mgreter** [comment]
Thanks for the hint, seems like that did it! https://github.com/sass/libsass/pull/925

**Comment by am11** [comment]
:tada:

**Pull request merged**
