### PR TITLE
Makefile: Compiler-specific LDFLAGS

### PR DESCRIPTION
**Pull request by glebm**
Detects compiler family by compiling and running a tiny C file on every invocation of make (30ms on my machine).

Alternative to #2720

### CODE REVIEW

**Comment by mgreter** [comment]
Seems coverage reporting by the target `(AUTOTOOLS=no COVERAGE=yes BUILD=static)` has broken. Maybe we should set coverage for this target to no (we still have to valid results). @glebm maybe you could adjust `.travis.yml`?

**Comment by glebm** [comment]
> Seems coverage reporting by the target (AUTOTOOLS=no COVERAGE=yes BUILD=static) has broken

It's been broken for a while, not by this PR

**Comment by mgreter** [comment]
Yep, I know, sorry, didn't want to blame your commit :) But maybe you'd have time to clean it up :)

**Comment by mgreter** [comment]
Ok, we just need to change COVERAGE=YES to NO in travis.yml. I'll see if I have time to make a PR.

**Comment by alyssais** [comment]
On second thoughts, I’m not actually sure this is going to solve my problem. Solaris generally uses the GCC _compiler_, but not its _linker_. And this is checking the compiler, right?

**Comment by glebm** [comment]
@alyssais This is checking the compiler but these flags are passed to `$(CC)`. I'm not sure how the linker gets invoked. Can you try this on Solaris?

**Comment by glebm** [comment]
@alyssais Oh, you're absolutely right. :man_facepalming:

**Pull request closed without merging**
