### PR TITLE
Fix SmartOS compilation once and for all

### PR DESCRIPTION
**Pull request by mgreter**
Verified by compiling inside VMWare image (the problems with `SEC` were present):
```
SunOS smartos 5.11 joyent_20160108T173524Z i86pc i386 i86pc
```

Let's see what CI thinks ... https://github.com/sass/libsass/issues/1802

### CODE REVIEW

**Comment by mgreter** [comment]
The last commit [reverts the SunOS specifics] [1] in the Makefile:

1) We need to have `libtool` installed and `ginstall` is not available by default too!
2) We install to `/` on all platforms (use `PREFIX="/opt/local"` to override).

SmartOS needs: `pkgin install automake autoconf libtool`!
Then we can also build libsass via autotools as [documented] [2].

[1]: https://github.com/sass/libsass/commit/2e0e379411e5a20dda88c9936a4126f6ac323ef8
[2]: https://github.com/sass/libsass/blob/master/docs/build-with-autotools.md

**Comment by xzyfer** [comment]
@jaredmorrow @djensen47 I'd like to hear your thoughts here

**Comment by mgreter** [comment]
Looks like `ginstall` would still be the correct one to use. libtool install doesn't seem to do the right thing, was asuming it would. But no idea how to get gnu-install on to SmartOS. Maybe if someone can argue why we cannot install into `/` on Solaris, please enlighten me.

**Comment by mgreter** [comment]
Verfied both install methods and documented my findings. Very very sure this chapter can be closed!

**Comment by mgreter** [comment]
I'm going to merge this on my responsibility. Beside CI I have tested it with Visual Studio 2013 Community, SmartOS 5.11, Gentoo Linux, Cygwin and MinGW. Not all combinations, but a fair share.
Want to move forward and concentrate to bring sass 3.4.21 parity!
As always feel free to open issues when problems arise.
Have a nice day!

**Pull request merged**
