### PR TITLE
Refactor output emitter and implement missing output styles

### PR DESCRIPTION
**Pull request by mgreter**
This superseeds https://github.com/sass/libsass/pull/899

Related to https://github.com/sass/sass-spec/pull/270 and https://github.com/sass/sassc/pull/97

- Heavily refactored output code
- Should make source maps more reliable
- Output styles are mostly done in emitter.cpp
- Refactored Parser (added new String type)
- Interpolation should now work as with ruby sass
- Commented out obsolete code (missing spec tests?)

Fixes
- #552 libsass doesn't preserve newlines
- #615 Interpolation inside an interpolation isn't handled correctly
- #639 Interpolation mangles up lists
- #694 Interpolation of quoted strings differs from Ruby SASS
- #870 Fix string-interpolation of lists, and normalization of string-quoting
- #876 Interpolations are parsed incorrectly
- #838 Support 'compact' output style
- #894 `SASS_STYLE_COMPRESSED` fails to eliminate empty rules with comments
- libsass-todo-tests/186 and libsass-todo-tests/scss-tests/172
- partially libsass-todo-tests/css_nth_selectors

### CODE REVIEW

**Comment by mgreter** [comment]
@xzyfer IMHO this is ready to be merged! Anything speaking against it from your side? What do you think about the changes in the spec-test? Really hope everything is still in order :sweat_smile:

**Comment by xzyfer** [comment]
The only think that jumped out at me is https://github.com/sass/sass-spec/pull/270#issuecomment-76639465.  Otherwise :+1:

**Comment by am11** [comment]
:+1:

**Comment by am11** [comment]
AppVeyor builds are failing for VC: https://ci.appveyor.com/project/sass/libsass/build/1.0.200.

Adding `output_nested` and `output_compressed` in `win/libsass.vcxproj` and applying the following patch would fix it:

```diff
diff --git a/inspect.cpp b/inspect.cpp
index d58dd3c..f3998b1 100644
--- a/inspect.cpp
+++ b/inspect.cpp
@@ -6,6 +6,7 @@
 #include <string>
 #include <iostream>
 #include <iomanip>
+#include <stdint.h>
```

**Comment by mgreter** [comment]
@am11 I've added the additional header you mentioned in your comment above, but output_nested and output_compressed have been removed actually (or I did not understand your comment)!

**Comment by am11** [comment]
@mgreter, yes actually the error was about files not found (because they were referenced in vcxproj but were removed from repo). :smiley: 

It is now complaining that we need `#include<stdint.h>` in util.cpp.
https://ci.appveyor.com/project/sass/libsass/build/1.0.207/job/bbhkel9xigunkppk#L950

Would it make sense to add headers in `.hpp`s, so when the header is used by multiple `.cpp`, it shares forward declarations for those lang features?

**Comment by am11** [comment]
All Green! https://ci.appveyor.com/project/sass/libsass/build/1.0.208. 
Yay! :tada:

**Comment by mgreter** [comment]
Thanks for the help with the appveyor ci build! :rocket:

**Comment by am11** [comment]
@mgreter, there are around [266 warnings](https://ci.appveyor.com/project/sass/libsass/build/1.0.208/job/segk9rjviip2dk7j#L1005) in VC job on AppVeyor. Some warnings are ignorable (POSIX style vs. STD-C++ style like `_stdup`).
But others may be useful. Like there are 100+ warnings regarding this error `C4099`: https://msdn.microsoft.com/en-us/library/695x5bes.aspx.

> 'Sass::Context' : type name first seen using 'struct' now seen using 'class'

(and vice versa)

For instance, in `bind.hpp` you have `struct Context`, while elsewhere it is used as class. Would it be a good idea to visit those warnings, it might improve some code patterns. :)

**Comment by mgreter** [comment]
Maybe someone that actually uses MSVC could create a patch to solve these warnings? Beside a struct is principally just a class with all variables defined as public ... but wouldn't hurt to get rid of these. We also would have a copy_c_str function which could act as a replacement for strdup.

**Comment by mgreter** [comment]
Since nobody has any objections against it, I'm going to hit "merge" here in a few minutes!

**Comment by am11** [comment]
Sure. I will try to take a stab at those soon. :smiley:

**Comment by xzyfer** [comment]
Amazing work @mgreter !!

**Pull request merged**
