### PR TITLE
Bugfix delayed interpolation

### PR DESCRIPTION
**Pull request by mgreter**
@xzyfer this is what I have come up with so far. I don't seem to be able to get it 100% correct for 3.4 as there always seem to be some other subtle regressions (which our specs do not catch currently). AFAIR I also got it correctly in regard to sass 4.0 and the following spec test at some point:

``` scss
tst {
  a01: (#{a} - 5% / 2);
  a11: (#{a} + 5% / 2);
  a02: (#{a} -5% / 2);
  a12: (#{a} +5% / 2);
  a03: (#{a}-5% / 2);
  a13: (#{a}+5% / 2);
  b01: (a - 5% / 2);
  b11: (a + 5% / 2);
  b02: (a -5% / 2);
  b12: (a +5% / 2);
  b03: (a-5px / 2);
  b13: (a+5px / 2);
}

tst {
  a01: (#{a} - 5.0% / 2);
  a11: (#{a} + 5.0% / 2);
  a02: (#{a} -5.0% / 2);
  a12: (#{a} +5.0% / 2);
  a03: (#{a}-5.0% / 2);
  a13: (#{a}+5.0% / 2);
  b01: (a - 5.0% / 2);
  b11: (a + 5.0% / 2);
  b02: (a -5.0% / 2);
  b12: (a +5.0% / 2);
  b03: (a-5.0% / 2);
  b13: (a+5.0% / 2);
}

tst {
  test-01: a #{5.0px / 2};
  test-02: a #{+5.0px / 2};
  test-03: a #{-5.0px / 2};
  test-04: #{+5.0px / 2};
  test-04: #{-5.0px / 2};
  test-04: #{5.0px / 2};
  test-04: #{a} -5.0px / 2;
}

tst {
  test-05: (a 5.0px / 2);
  test-06: (#{a} 9.0px / 2);
  test-0A: (5.0px / 2 a);
  test-07: (9.0px / 2 #{a});
  test-08: (9.0px / 2 #{a} 9.0px / 2);
  test-09: (a 5.0px / 2 #{a} 9.0px / 2);
  test-10: (a, 5.0px / 2 #{a} 5.0px / 2);

  test-11: (9.0px / 2 #{a} 9.0px / 2 #{a});
  test-12: (9.0px / 2 #{a} #{a} 9.0px / 2);
  test-13: (#{a} 9.0px / 2 #{a} 9.0px / 2);
  test-14: (#{a} 5.0px / 2 5.0px / 2 #{a});

  test-15: a 5.0px / 2;
  test-16: #{a} 9.0px / 2;
  test-17: 9.0px / 2 #{a};
  test-18: 9.0px / 2 #{a} 9.0px / 2;
  test-19: a 5.0px / 2 #{a} -9.0px / 2;
  test-20: a, 5.0px / 2 #{a} 5.0px / 2;

  test-21: 9.0px / 2 #{a} 9.0px / 2 #{a};
  test-22: 9.0px / 2 #{a} #{a} 9.0px / 2;
  test-23: #{a} 9.0px / 2 #{a} 9.0px / 2;
  test-24: #{a} 5.0px / 2 5.0px / 2 #{a};
}
```

### CODE REVIEW

**Comment by xzyfer** [comment]
We're going to leave this for now. There are some bugs in Ruby Sass that should be fixed first.

https://github.com/sass/sass/issues/2160

**Comment by mgreter** [comment]
I think we might need one or two fixes from here as I saw some regressions not catched by CI.

**Comment by xzyfer** [comment]
I'll take a closer at this after the 3.4 RC, and aim to get this into 3.4 stable.

As for 869a51a, is there a spec for what this is addressing? I should be in it's own PR.

**Comment by mgreter** [comment]
> As for 869a51a, is there a spec for what this is addressing? I should be in it's own PR.

Sorry, but I don't understand this? Did you mean issue? If so, no there is not!

**Comment by mgreter** [comment]
It may address the same as you fixed lately though ... it's tagged WIP for a reason

**Comment by xzyfer** [comment]
It's not clear to me from the PR description what role 

>Improve extending of wrapped ":not" selectors

Plays in addressing a bug with interpolating of property values. My comment was simply that this PR appears to be addressing two unrelates issues.

**Pull request closed without merging**
