### PR TITLE
feature(sass_context): adding sass_context_take_included_files()

### PR DESCRIPTION
**Pull request by rodneyrehm**
fixing #982

### CODE REVIEW

**Comment by mgreter** [comment]
@rodneyrehm I guess you already have tested it? I guess it should be ok, but I'm a bit worried because it's a `char**` in this case ...

**Comment by rodneyrehm** [comment]
Yes, I've successfully tested in in my context - but I haven't written any tests for it (as coveralls already reported).

I don't understand why you're worried, it is a `char**` in the first place and considering all the function does is null the pointer so it doesn't get cleaned later. I didn't see a difference to how `char *` is handled. That said, I have **no** idea what I'm doing - I'm rather happy I'm able to spell "C" ;)

**Comment by mgreter** [comment]
I come to the same conclusion as you with `char**`, it's just that it is slightly different than all the others and it often tends to bite me in the ass if I just blindly trust my logic :wink: Going to merge this since you confirmed that it at least works in your context. Impacts are pretty slim with this function anyway!

Thanks for the contribution @rodneyrehm !
BTW. On my todo list also to update sass.link.js :smile:

**Comment by rodneyrehm** [comment]
Thanks for merging!

> BTW. On my todo list also to update sass.link.js

I'm currently looking at [API Sass Importer](https://github.com/sass/libsass/wiki/API-Sass-Importer) and how I can integrate that into sass.js - that should go a long way to simplify your sass.link.js, no? I'll open an issue for that wiki page, as I have questions to ask / discoveries and opinions to share.

**Pull request merged**
