### PR TITLE
Reorganize headers into `sass` subfolder

### PR DESCRIPTION
**Pull request by mgreter**
May add more info later here ... Fixes https://github.com/sass/libsass/issues/1360
Corresponding PR for sassc: https://github.com/sass/sassc/pull/142
Travis-CI test-run (with [legacy headers] [1] to make it pass):
https://travis-ci.org/mgreter/libsass/builds/78975306

[1]: https://github.com/mgreter/libsass/commit/4278f0d622ac7636e1c2f76daa878118f4ec0893

### CODE REVIEW

**Comment by xzyfer** [comment]
LGTM

**Comment by saper** [comment]
Maybe we should use `libsass` directory, as this is related to this implementation and not to some genetic Sass C API which does not exist ATM.

**Comment by mgreter** [comment]
We already install `libsass.so`, so IMO we've already taken that name ...

**Comment by saper** [comment]
This breaks out-of-tree configure build (`cd somedir && $source/configure`):

````
config.status: error: cannot find input file: `include/sass_version.h.in'
````

**Comment by am11** [comment]
:+1:

**Pull request merged**
