### PR TITLE
Add prelexer for decimal value with trailing zeroes

### PR DESCRIPTION
**Pull request by maximus8891**
Resolves: #1216

### CODE REVIEW

**Comment by xzyfer** [comment]
Given that the referenced issue is closed, can you please provide an
example of exactly what this is fixing?

**Comment by maximus8891** [comment]
There was a spec created for #1216 and it is still in the todo list. I wanted to close it.

I can updated the spec to match the current output and close this PR. However, first I wanted to check that the behaviour is correct. Given `3.0px`, the output is `3.0px`. Would not contracting `3.0px` to `3px` save space?

In #550 it worked the other way round. `.001px` was extended to `0.001px` adding a character.

**Comment by nschonni** [comment]
@nex3 Dart seems to be pruning trailing zeros. Is that a new feature or a bug?

**Comment by nex3** [comment]
@nschonni The answer to that question is multi-layered! Strap in!

How an implementation chooses to serialize its final AST to CSS is up to that implementation, as long as the CSS is semantically identical to the specified CSS. As far as CSS is concerned, `3.0px` and `3px` are the same value, so implementations are free to switch between them as they choose.

Ruby Sass does this too! For example, Ruby Sass will compile `a { b: (3.0px); }` to `a { b: 3px; }`. *However*, Ruby Sass has special logic for "static" property values that look like they don't include any SassScript. As a mitigation for Ruby Sass's incredible lack of speed, it avoids fully parsing or interpreting static values and instead passes them on as-is to the CSS output. So if you don't include parentheses, Ruby Sass won't change the input at all and you'll get `3.0px`.

Dart Sass, on the other hand, is much faster than Ruby Sass and as a consequence has no special handling for static property values. It fully parses every value and converts it to CSS using its normal logic, which means that its numbers *always* have trailing zeroes trimmed.

So it's not a bug, but it's not *exactly* a feature either. I guess I'd call it a "non-semantic implementation difference".

**Comment by xzyfer** [comment]
I'm in favour of updating the LibSass output of the spec and moving on.

**Comment by maximus8891** [comment]
Makes sense, especially that there are other specs that have conversions from `opacity: 1.0;` to `opacity: 1.0;`.

**Pull request closed without merging**
