### PR TITLE
Replace `String_Quoted` with `String_Constant` in parser where possible

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/1328 and https://github.com/sass/libsass/issues/1295

### CODE REVIEW

**Comment by xzyfer** [comment]
\o/ (hooray!)

**Comment by xzyfer** [comment]
Happy to merge this!

I'd love a quick explanation though as to why this fixes the issue. I am not clearer on when to a quoted string vs a constant.

**Comment by mgreter** [comment]
Basically `String_Constant` are literals, while `String_Quoted` are actual strings with semantics. Internally we store the latter in unquoted form and decide on output if we should quote them again (usefull for comparison to literals or concatenation). AFAIR, we previousely had the flag `needs_unquote`, which basically represented the same as these two string classes. I basically just introduced them for interpolation; but I guess there is a difference between actual sass string values and i.e. static expressions (where ruby sass even preserves block comments).

As you know interpolation is still a mess, and fixing that will definitely help clearing up the mess with the string classes. BTW: the list without spaces is `String_Schema`, but output (escaping) is off to ruby sass ...

**Comment by xzyfer** [comment]
Thanks for the explanation.

**Comment by dennisfrank** [comment]
Thanks guys! :)

**Pull request merged**
