### PR TITLE
Add support for nth with maps

### PR DESCRIPTION
**Pull request by xzyfer**
This PR add support for `nth` with maps.

> This can return the nth pair in a map as well. - http://sass-lang.com/documentation/Sass/Script/Functions.html#nth-instance_method

Fixes https://github.com/sass/libsass/issues/643. Specs added https://github.com/sass/sass-spec/pull/134.

### CODE REVIEW

**Comment by mgreter** [comment]
FYI: I get a success for this test with https://github.com/sass/libsass/pull/1600

**Comment by xzyfer** [comment]
@mgreter I'm not sure what you mean.

**Comment by mgreter** [comment]
I got a positive result with my test runner with that branch!
Wondering why now or put different, why did it not pass before?

**Comment by xzyfer** [comment]
I'm confused because the spec should have always passed. I'm not following
what your PR has to do with this old feature.

**Comment by mgreter** [comment]
Me neither, that's why I posted here, since it seems this is still in todo?

**Comment by xzyfer** [comment]
As far as I can tell this spec (https://github.com/sass/sass-spec/pull/134) as activated 11 months ago.

**Pull request merged**
