### PR TITLE
[DNM] CMake build files and directory structure

### PR DESCRIPTION
**Pull request by nschonni**
# DO NOT MERGE
The commits really need to be cleaned up before this can be merged.

- Replace Make/autotools with [CMake](http://cmake.org) for cross platform building.
- Loose layout based on https://code.google.com/p/cpp-library-project-template/
- Each namespace moved to folders below `src`
- Adds version information 
- Testing is invoked through CTest for now, but this only gives the full output for the specs when using the verbose flag
- Existing test harness under the test folder all pass currently because CTest expects a non-zero exit for failures
- Base setup for Doxygen generation, but not fully plumbed

TODO
 - [x] Rebase down commits
 - [x] Remove Boost/Unit++ commented out code
 - [ ] Look at replacing GLOB_RECURS for tests
 - [x] Update all license top license lines with actual content
 - [x] Exclude generated version info file
 - [ ] Emscripten binding using https://github.com/kripken/emscripten/blob/master/cmake/Platform/Emscripten.cmake

### CODE REVIEW

**Comment by am11** [comment]
:+1:
Another repo which has integrated CMake recently: https://github.com/neovim/neovim.

**Comment by mgreter** [comment]
I have picked up on this work and successfully built the dll with cmake and msbuild (https://github.com/sass/libsass/pull/1352). Bot sure if it will make it to master anytime soon, but getting the first results was rather easy! But there are still some open things, like versions and header location. Maybe somebody wants to continue from there ...

Going to close this once I can create a clean PR with my changes!

**Comment by nschonni** [comment]
That's great @mgreter !

**Comment by mgreter** [comment]
I'm going to close this since it is superseded by #1359.

**Pull request closed without merging**
