### PR TITLE
Add a join us in slack button to the readme

### PR DESCRIPTION
**Pull request by xzyfer**
This PR adds a button to join us our Slack channel to the README.

screen shot 2015-04-16 at 7 07 03 pm

This will in essence replace the gitter chat room which to this date has host 2 short conversations.

/cc @mgreter @hcatlin @chriseppstein

### CODE REVIEW

**Comment by xzyfer** [comment]
Turns out due to changes in the API this is currently a non-started.

https://github.com/rauchg/slackin/issues/38
https://github.com/rauchg/slackin/issues/16

**Comment by drewwells** [comment]
Requested invite!

**Comment by xzyfer** [comment]
Unfortunately as per my follow up comments this doesn't work. If you send
me your email address I can invite you.

**Comment by drewwells** [comment]
Where should I send my email?

**Comment by xzyfer** [comment]
My GH handle on twitter or at gmail.

On 4/17/15, Drew Wells <notifications@github.com> wrote:
> Where should I send my email?
>
> On Thu, Apr 16, 2015 at 6:07 PM Michael Mifsud <notifications@github.com>
> wrote:
>
>> Unfortunately as per my follow up comments this doesn't work. If you send
>> me your email address I can invite you.
>> On 17 Apr 2015 02:27, "Drew Wells" <notifications@github.com> wrote:
>>
>> > Requested invite!
>> >
>> > On Thu, Apr 16, 2015 at 5:38 AM Michael Mifsud
>> > <notifications@github.com
>> >
>> > wrote:
>> >
>> > > Turns out due to changes in the API this is currently a non-started.
>> > >
>> > > rauchg/slackin#38 <https://github.com/rauchg/slackin/issues/38>
>> > > rauchg/slackin#16 <https://github.com/rauchg/slackin/issues/16>
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/sass/libsass/pull/1110#issuecomment-93704533>.
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/sass/libsass/pull/1110#issuecomment-93777866>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sass/libsass/pull/1110#issuecomment-93859229>.
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sass/libsass/pull/1110#issuecomment-93862304


-- 
Regards,
Michael

**Comment by xzyfer** [comment]
With some finagling I've managed to get this working. We're back in business!

**Pull request merged**
