### PR TITLE
Fix and prepare memory manager for reference counting

### PR DESCRIPTION
**Pull request by mgreter**
Inherit from base class `Memory_Object` to let the
compiler optimize for memory alignment.

### CODE REVIEW

**Comment by xzyfer** [comment]
@mgreter is this related to https://twitter.com/rodneyrehm/status/641610148524478464 ?

**Comment by mgreter** [comment]
I think so!

**Comment by xzyfer** [comment]
Tested locally, all seems well.

@rodneyrehm can you confirm whether this fixes the Sass.js issue?

**Comment by rodneyrehm** [comment]
nice! yes, this fixes my issue :)

**Comment by am11** [comment]
:+1:

**Comment by xzyfer** [comment]
Ready for this to ship when you are @mgreter

**Pull request merged**
