### PR TITLE
Bad code fragment

### PR DESCRIPTION
**Pull request by MrBenGriffin**
Need to allocate memory for data context..

### CODE REVIEW

**Comment by mgreter** [comment]
https://github.com/sass/libsass/pull/2968

**Comment by mgreter** [comment]
I've merged my doc changes, please see if anything else should be added. Thanks!

**Comment by MrBenGriffin** [comment]
That’s brilliant.

On a different note, an earlier version of libsass would send some error and warning messages to “cerr” - I’m hoping that this doesn’t happen any more?  Is there an option to be able to add a custom logging handler? I think we are currently parsing the return string..

**Comment by mgreter** [comment]
We still print to stderr, see https://github.com/sass/libsass/pull/2862

**Pull request closed without merging**
