### PR TITLE
Fixes performance bottleneck in subset_map/extend

### PR DESCRIPTION
**Pull request by mgreter**
You can expect to see a 2x performance increase in bigger sass code bases. With more extend usage it can go as high as 10x performance increase.

Test with styles of a real corporate website showed a performance increase of 3x (from 750ms to 250ms). When I imported the main stylesheet 10x times, compile time went from 100s to 5s (~20x increase).

This indecently (according to probe-todo) also fixes https://github.com/sass/libsass/issues/2056 (false positive?)?

### CODE REVIEW

**Comment by xzyfer** [comment]
It's noting that the expected behaviour of #2056 has changed. The bug is now incorrect, see the final comments.

**Comment by xzyfer** [comment]
Nice one. This approach is fine by me. It's worth nothing that the extends behaviour has changed slightly in dart-sass, whose behaviour is going to be the reference implementation.

**Comment by mgreter** [comment]
As stated, this looks like a false positive (therefore meaning probe-todo is still broken) ...

**Comment by xzyfer** [comment]
Yeah. Just wanted to make sure you were aware of the difference between Ruby Sass and Dart Sass since you're working on the extends code.

**Comment by mgreter** [comment]
FWIW: made some performance assesments accross different implementations:

```scss
.clearfix {
  &:after {
    content: "";
    display: table;
    clear: both;
  }
}

@for $n from 1 through 100 {
	@for $i from 1 through 100 {
		.foo#{$i} { @extend .clearfix; }
	}
}
```

```cmd
$ bin/sassc.exe -v
sassc: 3.4.1
libsass: 3.4.0-19-g414b
sass2scss: 1.1.0
sass: 3.4
$ time sassc test.scss
real    0m0.279s
user    0m0.000s
sys     0m0.015s
```

```cmd
$ sass -v
Sass 3.4.23 (Selective Steve)
$ time sass test.scss
real    0m2.560s
user    0m1.984s
sys     0m0.561s
```

```cmd
$ dart-sass --version
1.0.0-alpha.6
$ time dart-sass test.scss
real    0m45.833s
user    0m0.000s
sys     0m0.000s
```

//CC @xzyfer @nex3

**Pull request merged**
