### PR TITLE
Respect `sass_string_is_quoted` when converting from C-API

### PR DESCRIPTION
**Pull request by mgreter**

### CODE REVIEW

**Comment by xzyfer** [comment]
:+1:

**Comment by xzyfer** [comment]
Is this good to go @mgreter?

**Comment by mgreter** [comment]
I may find more stuff once I get around to add more unit tests to perl-libsass. Otherwise this is good to go!

**Comment by saper** [comment]
Mentioning https://github.com/sass/libsass/issues/1143 for reference (not sure if it fixes the problems mentioned there).

**Pull request merged**
