### PR TITLE
Test CI - https://github.com/sass/sass-spec/pull/839

### PR DESCRIPTION
**Pull request by mgreter**
https://github.com/sass/sass-spec/pull/839

### CODE REVIEW

**Comment by mgreter** [comment]
Pretty funky that we got 5 CI checks here :confused:

**Comment by mgreter** [comment]
Damn, hit the wrong merge button. Well, nothing broken ...

**Comment by xzyfer** [comment]
You get 5 checks with you don't PR from a fork.

**Comment by mgreter** [comment]
ah, your right, thanks :bulb:

**Pull request merged**
