### PR TITLE
Additional fixes for 3.3 release

### PR DESCRIPTION
**Pull request by mgreter**
This PR contains all comits after the main parser refactoring (#1249)

### CODE REVIEW

**Comment by mgreter** [comment]
@xzyfer my other PR #1338 contains these commits. These are IMHO the most important ones. I guess we still can merge @saper un'std branch later (I guess it should fix the SUB OS problems for now). This one should be easy to review, so I hope we can get this into master ASAP!

**Comment by saper** [comment]
I have rebased un'std branch to the current master, so if the new code has `std::vector`, `std::string`, `std::map`, `std::pair`, `std::make_pair()`, `std::min()`, `std::max()` etc. it should merge easily... Would that be ok?

**Comment by mgreter** [comment]
@saper regarding the `AM_PROG_AR`. It works if I also add `m4_pattern_allow([AM_PROG_AR])` which I guess will tell it to ignore the error about not existing `macro `AM_PROG_AR' not found in library`. So does my commit actually fix the original problem? Other than that, I'm not too excited about getting rid of `using namespace std`. It just makes it more tedious to code around ...

**Comment by saper** [comment]
Well `using namespace std;` is a nice shortcut for simple trivial programs, but I am already having trouble to figure out issues with different compilers (Visual Studio redefining min/max https://github.com/saper/libsass/commit/23f89beef745936fbbb82bc95aa1efe19824a682, GCC breaking `std::round()` on non-glibc systems https://github.com/sass/node-sass/issues/1034, and of course the `SEC` problem on Solaris etc.). 

Actually I was surprised that most of the files use `std::string` or `std::vector` rather sparingly, for other `*.cpp` files (but not header files!) it is always possible to do `using std::string; using std::vector` to improve readability. That said - it easier to spot difference between `std::string` and `String`  (meaning `Sass::String`), and we also have a local variable named `string` somewhere...

Another example of related trouble is https://github.com/sass/libsass/commit/5445c456acd1db47608dd20cd267cb3e034c3c62 - you don't really know which `abs()` are you using and how stricter C++ type checking should work...

Only in `ast.hpp` readability is a bit worse - because this "header" file is doing lots of work (instead of `ast.cpp` file for example) and `ast.hpp` gets included almost everywhere, therefore all namespace imports get spoiled onto other files.

Even if this is developer's (slight) inconvenience, people trying to compile libsass on non-Linux platforms will certainly have a simpler job.

**Comment by mgreter** [comment]
@xzyfer This should be merged next for 3.3! Should not be too big for a review ;)

**Comment by mgreter** [comment]
List of fixed open issues:
- https://github.com/sass/libsass/issues/1259
- https://github.com/sass/libsass/issues/1298
- https://github.com/sass/libsass/issues/1305
- https://github.com/sass/libsass/issues/1332

**Comment by mgreter** [comment]
Gave it another reviewed and for me this is ready to :ship:

**Comment by xzyfer** [comment]
I'm not sure about some of the number changes. I need to give it a closer look. The semantics of `strict` aren't clear. It feels like a bit of a hack to me.

**Comment by xzyfer** [comment]
Please pull out f37cd95aef6aba4dd07f41b58b03b6eed1b938d9 into it's own PR. I want to take a closer look. 

The rest looks good to me.

**Comment by mgreter** [comment]
Remerged branch to have requested commit to be on top and created another PR that only includes that specific commit.

**Comment by xzyfer** [comment]
Wow yeah something is up with the commit list. Github think there were two different authors on the commits.

**Comment by xzyfer** [comment]
>Rebased branch to have requested commit to be the first in list

Why make it first? Please just remove the commit from this branch. It'll live on in your other PR.

**Comment by mgreter** [comment]
So this PR is ready once the other PR is merged! And yeah, messed up by using another client, bah.

**Comment by mgreter** [comment]
Removed as requested!

**Comment by xzyfer** [comment]
:ship: when CI is green!

**Pull request merged**
