### PR TITLE
Include Haskell bindings in implementations list

### PR DESCRIPTION
**Pull request by jakubfijalkowski**
Hello!

I'm an author of [hLibsass](https://github.com/jakubfijalkowski/hlibsass) and [hSass](https://github.com/jakubfijalkowski/hsass) and just wanted to add them to the known implementations list. They were listed in the Wiki, but must have been lost during conversion. :)

Cheers,

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks for this. Please maintain the alphabetic order.

**Comment by xzyfer** [comment]
I've cancelled the builds. Don't be alarmed.

**Comment by jakubfijalkowski** [comment]
Should I also move Java and JavaScript headings up in the list?

**Comment by xzyfer** [comment]
Please do

**Comment by jakubfijalkowski** [comment]
Fixed

**Comment by xzyfer** [comment]
Thanks!

**Comment by jakubfijalkowski** [comment]
Well, that was fast.

Thank you!

**Pull request merged**
