### PR TITLE
Add automatic git versions for vcxproj file

### PR DESCRIPTION
**Pull request by mgreter**

### CODE REVIEW

**Comment by am11** [comment]
:+1:

**Comment by xzyfer** [comment]
LGTM

**Comment by saper** [comment]
I think we should start generating `sass_version.h` files in any case. 

What happens here if git is unavailable/not in PATH/on strike?

**Comment by drewwells** [comment]
Building Go from source required a VERSION file whenever git was
unavailable. Looks like a decent approach.

`go tool dist: FAILED: not a Git repo; must put a VERSION file in $GOROOT`

**Comment by mgreter** [comment]
@saper if git is not available it will probably fail. We mainly use these files for CI and they are not polished enough anyway to build all possible combinations (static/shared). Heck they even have a hard reference to `sassc.cpp`, since we need that to run the spec test suite.

**Pull request merged**
