### PR TITLE
CI: Removes MinGW from cache

### PR DESCRIPTION
**Pull request by am11**
* Repo: Adds VS files to .gitignore.

### CODE REVIEW

**Comment by am11** [comment]
Before: https://ci.appveyor.com/project/sass/libsass/build/1.0.284/job/wtrhkkvd6qsux1s0#L445

After: https://ci.appveyor.com/project/sass/libsass/build/1.0.286/job/py6xwy85g9f6ue93#L464

**Comment by mgreter** [comment]
LGTM and CI seems to agree :smile:

**Comment by xzyfer** [comment]
LGTM! also...

> 28 min 53 sec
:sob:

**Comment by am11** [comment]
I have changed the title of this issue. The debug failure syndrome was back. 

But the rest of the changes will boost the performance from ~6 mins to ~2 mins per build.

@xzyfer, please merge it so all future commits get compiled quickly. :)

**Comment by am11** [comment]
@mgreter, that comment suggests that there were assertion errors when running the `sassc` command. Can you tell how did you diagnose it? I couldn't find it in the output. Is there a (hidden) verbose switch in sassc?

**Comment by xzyfer** [comment]
:heart_eyes: :heart_eyes: :heart_eyes:

**Comment by xzyfer** [comment]
Is this ready to go @am11 ?

**Comment by am11** [comment]
Yes @xzyfer! Debug can wait. :)

**Comment by xzyfer** [comment]
:boom: great work!

**Comment by mgreter** [comment]
@am11 it simply did not complete the spec tests in debug mode, so I simply switched that off! Seems like we have fixed it in the mean time and you were the first one to stumble up on it!

**Comment by am11** [comment]
@mgreter, it was working when I opened this PR and now it starting to fail again: https://ci.appveyor.com/project/sass/libsass/build/1.0.303, so I reverted back that line with `echo` prefix. I don't know why it was working before and why failing now. But the comment there suggests that it fails with assertion failure, on running tests with debug configuration.

Perhaps, get some verbose output from sassc to check where the Debug build goes all mute for hours.

**Pull request merged**
