### PR TITLE
Implement using & in SassScript

### LINKED ISSUE #548: Support parent selector & in values / and/or interpolations
Hi 

First I'd like to thank you for your awesome work! 

I've put together a small BEM Sass library http://codepen.io/gionkunz/pen/rkswl and there are problems in libsass with the parent selector. It looks like there is an undocumented feature in RubySass that the parent selector & can also be converted to a selector string. I believe internally its a list of lists if I'm not mistaken. So in `.test { .abc, .def { &:before { content: "." } } }`  & would be stored as list of lists `( ( ".test .abc" ) , (".test .def") )`. In RubySass when the parent selector `&` appears where a value is expected it gets converted to a string http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_functions .

```css
.parent-sel-value {
  font-family: &;
  .parent-sel-interpolation {
    font-family: #{&};
     .parent-sel-value-concat {
        font-family: "Current parent: " + &;
     }
  }
}
```

Gets processed to:

```css
.parent-sel-value {
  font-family: .parent-sel-value;
}
.parent-sel-value .parent-sel-interpolation {
  font-family: .parent-sel-value .parent-sel-interpolation;
}
.parent-sel-value .parent-sel-interpolation .parent-sel-value-concat {
  font-family: "Current parent: .parent-sel-value .parent-sel-interpolation .parent-sel-value-concat";
}
```

This feature is particularly interesting for libraries and frameworks that need to have more control over selectors during nesting. I'd really love to have this in libsass too. 

I did not find any spec in https://github.com/sass/sass-spec concerning this undocumented feature and I'd also help where I can to get this in.

Cheers
Gion

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5348667-support-parent-selector-in-values-and-or-interpolations?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by xzyfer**
This PR implements using & in SassScript.

Fixes #548. Specs added https://github.com/sass/sass-spec/pull/103, https://github.com/sass/sass-spec/pull/280.

Successor to #965, #959

/cc @ekskimn

### CODE REVIEW

**Comment by xzyfer** [comment]
Once again great work here @ekskimn! I'll merge this once CI passes.

**Comment by ekskimn** [comment]
Thanks @xyfer, sorry for the pr mess.  I tried doing the fixup commit but yeah it ended up being another commit somehow.

**Comment by xzyfer** [comment]
No worries! Feel free to join our gitter (https://gitter.im/sass/libsass) and we can catch about how to avoid merge commits :)

Unfortunately the really mess up the git history and make it have to back out changes or forensically figure when something broke.

**Comment by mgreter** [comment]
Congrats @ekskimn for such a great contribution. Hope you stay around and would love to see more contributions of that quality. One major feature off the checklist, great suff!

**Comment by am11** [comment]
:+1: :100: 
Congrats @ekskimn! :tada: 

@xzyfer, I didn't knew that we are keeping `libsass.filters` in sync too (not even sure what is it for).

**Comment by xzyfer** [comment]
@am11 me neither. I just greped for `cssize` and did the same. I'm pretty sure when I wrote `cssize` I just greped for `expand`... etc..

**Comment by ekskimn** [comment]
@mgreter Most definitely sticking around.  Glad to contribute something even if @xzyfer still seems uncomfortable with it.  Considering doing #963 next

**Comment by xzyfer** [comment]
#963 would be great! I'd make sure to start with a thorough spec suite first.

**Comment by geddski** [comment]
sweet! This is the main feature I've been waiting for to be able to use libsass with [csstyle](http://www.csstyle.io/). Thanks @xzyfer!

**Comment by JerseyMilker** [comment]
Thank you!  PS. Check out geddski's csstyle sometime, it's pretty slick :)

**Pull request merged**
