### PR TITLE
Added support to multiline declarations in indented syntax

### PR DESCRIPTION
**Pull request by cemelo**
I'm not an expert in C++, but, since this problem has been annoying me for a while, I decided to create a patch to libsass in order to support multiline declarations.

This patch creates a `preprocess` function that concatenates a line with its subsequent when one of the following situations occur:

- the line ends with a backslash;
- the line ends with a comma;
- the parenthesis for that declaration aren't balanced.

### CODE REVIEW

**Comment by xzyfer** [comment]
Please open this PR against the sass2scss repository.

**Comment by cemelo** [comment]
Sorry about that. Didn't know sass2scss was a different project.

**Comment by henrahmagix** [comment]
@cemelo Can you add this to `sass2scss` please? I would really really like this for long maps

**Comment by xzyfer** [comment]
@cemelo no worries, we appreciate your work. If you could PR sass2scss we could get this into the next release.

**Comment by cemelo** [comment]
@henrahmagix @xzyfer Sorry for the delay. I'll try to push it in the next couple of days.

**Comment by henrahmagix** [comment]
Brill, thanks!

**Pull request closed without merging**
