### PR TITLE
README: Updates compiler versions

### PR DESCRIPTION
**Pull request by am11**
* GCC 4.5 -> 4.6.
* Adds instructions for Windows.

### CODE REVIEW

**Comment by xzyfer** [comment]
Thanks!

**Comment by am11** [comment]
:tada:

**Comment by patlecat** [comment]
Can I ask why libsass wants to be compatible with such an old compiler? What is the point?

**Comment by xzyfer** [comment]
It enables us to reach the largest audience. In our experience people tend
not to update their compilers. More often than not we're dealing with the
OS default. Notably older CentOS users have very old compilers, lower than
even we support.

**Comment by patlecat** [comment]
Ah that's why you demand the use of Visual Studio 2013 Upd4 (the latest) just to support a larger audience? LOL No seriously, why do you do it? Why not just say GCC 4.8.2 is the minimum?

**Comment by am11** [comment]
AFAICT libsass doesn't compile below VS2013 Update 2. The C99, C++11 features were not available in older iterations of VS (see [this vcblog entry](http://blogs.msdn.com/b/vcblog/archive/2013/12/02/c-11-14-core-language-features-in-vs-2013-and-the-nov-2013-ctp.aspx)).

Besides GCC v4.6 *is* the minimum version which can compile libsass. Why should we misguide the users? It does not make sense.

**Pull request merged**
