### PR TITLE
Use case-insensitive lookup to parse colors.

### LINKED ISSUE #2462: Colors should be case insensitive?
## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
a { b { color: lighten(Crimson, 10%); } }
```

## Actual results

```
$ ./node_modules/.bin/node-sass --version
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
$ ./node_modules/.bin/node-sass test.scss test.scss  |& jq --raw-output .message
argument `$color` of `lighten($color, $amount)` must be a color

Backtrace:
	test.scss:1, in function `lighten`
	test.scss:1
```

## Expected result

```
$ sass --version
Sass 3.5.1 (Bleeding Edge)
$ sass test.scss
a b {
  color: #ed365b; }
```

Originally reported in https://github.com/dahlia/libsass-python/issues/214

### PR DESCRIPTION
**Pull request by asottile**
Fixes #2462
Spec https://github.com/sass/sass-spec/pull/1161

### CODE REVIEW

**Comment by mgreter** [comment]
LGTM, since colors should always only contain ASCII characters. THX!

**Comment by asottile** [comment]
The build seems to have timed out?  Perhaps it can be restarted

**Comment by xzyfer** [comment]
@asottile bumped the build

**Comment by nschonni** [comment]
Failure seems related to https://github.com/travis-ci/travis-ci/issues/6307
I'll try some fixes separately

**Comment by xzyfer** [comment]
@nschonni I think that is a red herring. The build fails due to the proxy being down

```
Fetching PR 2463
Travis rate limit on github exceeded
Retrying via 'special purpose proxy'
curl: (7) Failed to connect to libsass.ocbnet.ch port 80: Connection refused
The command "./script/ci-build-libsass" exited with 7.
```

Everything else is a consequence on that. I'll update LibSass to use the heroku proxy I created for node-sass to stop this ever happening again.

**Comment by xzyfer** [comment]
Backported to 3.4

**Pull request merged**
