### PR TITLE
Fix bug in C-API with context compiler status

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/1035 @am11, @rodneyrehm can you test if this fixes your issues?
This does NOT alter the existing public (beta) API, only internal changes!

### CODE REVIEW

**Comment by rodneyrehm** [comment]
Looks like this PR fixes the problem!

---

tested the following way:

```
# cd libsass
git checkout master && git fetch --prune && git pull --rebase
git remote add mgreter git@github.com:mgreter/libsass.git
git fetch mgreter
git merge mgreter/bugfix/issue_1035
# building my stuff
```

is there a simpler way to locally merge a PR manually adding all PRs to `.git/config`:

```
[remote "origin"]
  url = git@github.com:sass/libsass.git
  fetch = +refs/heads/*:refs/remotes/origin/*
  fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```

**Comment by drewwells** [comment]
This is how I do it
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by mgreter** [comment]
Thanks @rodneyrehm for the positive news! Again sorry for messing that one up! Going to merge this now, since I can confirm that node-sass does not segfault anymore (@am11 only one test failing) !

**Comment by rodneyrehm** [comment]
splendid, thank you for the quick fix!

**Comment by am11** [comment]
@mgreter, thanks! Should I wait for the next beta?

@rodneyrehm, I always tend to use pull with rebase. :)

Once I added the remotes after the first clone:

```bash
# first time
cd src/
git clone https://github.com/sass/libsass
cd libsass
git remote add mgreter-libsass https://github.com/mgreter/libsass
git remote add xzyfer-libsass https://github.com/xzyfer/libsass
```

later at any random point in time:

```bash
cd src/libsass
git pull --rebase mgreter-libsass feature-branch-name
```

(it fetches and rebase on your current branch and fallbacks to 3-way merge if there are conflicts which normally doesn't happen if you have added libsass as submodule like node-sass has)

**Comment by mgreter** [comment]
@am11 use the latest master to update node-sass to. When you are ready to release a new beta for node-sass please, ping us and we will make another libsass beta!

**Pull request merged**
