### PR TITLE
Add fix for hsla implementation

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/1101 (added to 3.2. since the bug is obvious)

### CODE REVIEW

**Comment by xzyfer** [comment]
I think this can wait to 3.2.1. We've cleared out the 3.2.0 regressions, we should ship it ASAP.

We don't have great test coverage here, and this isn't a regression.

**Comment by mgreter** [comment]
I don't have any personal preference here, but the Bug is very obvious and the fix should not have any side-effects. Saturation/lightness must have a value between 0 and 100 and hue has to be between 0 and 360 degrees. But feel free to descope it makes you feel uneasy :)

**Comment by xzyfer** [comment]
Ok cool, lets merge this and ship 3.2.0?

**Comment by mgreter** [comment]
I would say so :+1: Just left it open for proper peer review ;)

**Comment by xzyfer** [comment]
I haven't had a chance to look into the issue, but I trust your judgement :) lets do it!

**Comment by mgreter** [comment]
You saw the changes in this PR? They are very trivial!

**Comment by xzyfer** [comment]
:smile: merged

**Comment by xzyfer** [comment]
I'll put together the complete release notes for 3.2.0 and get started on node-sass 3.0.0 stable.

**Comment by mgreter** [comment]
:+1: :ship:

**Pull request merged**
