### PR TITLE
Fixing Warnings with MSVS 2015

### PR DESCRIPTION
**Pull request by driekus77**
In this commit/push I reversed previous pull request changes and fixed only the warnings as pointed out by the MSVS 2015 C/C++ compiler.

Code analysis issues will follow soon in another request.

### CODE REVIEW

**Comment by xzyfer** [comment]
@driekus77 some of these fixes have been cherry-picked onto master. Could you please base this PR off master?

**Comment by driekus77** [comment]
My experience with git(hub) is lacking: What do you meen with "Could you please base this PR off master?”

Rebase or Create a branch on driekus77:libsass which is more describing?

Kind regards,

Henry

**Comment by saper** [comment]
This is actually more related to the `git` version control utility and not GitHub as such.

Your commit series starting with b3b564d was done when a61117a492dbcb56b495d441cdad34d8d2ed was the top of the master. (This is normal, you have started your modifications at the time).

In the meantime the work on libsass progresses and the master advanced from a61117a4 to the (current as I write this) - those are 29 commits:

````
 git log --oneline master ^a61117a4
9b4e424 Merge pull request #1395 from xzyfer/fix/json-signature-mismatchg
8367adf Update some methods in json.cpp to be more interally consistent
ce1f6c2 Fix mismatch in function signature in json.cpp
666d2c0 Merge pull request #1342 from mgreter/feature/number-fixes
e154e5c Merge pull request #1373 from drewwells/feature/jsonpreprocessor
7ed376f Merge pull request #1389 from mgreter/bugfix/issue-1376
fe37d44 Merge pull request #1391 from mgreter/code-improvements
50bcd62 Fix a few obvious code issues
046e78f Fix interpolation of lists with null values
92be77a Merge pull request #1388 from mgreter/fix/msvc-warnings
434327b Merge pull request #1363 from mgreter/fixes/issue_1355
c522143 Make empty `@return` statement a parser error
a303263 Add concrete types for all statements
c6d43fd Fix a few MSVC warnings
d17ab21 Merge pull request #1387 from mgreter/fix/pointer-compare
b4e24d7 Remove pointer compare functions
7014f55 Merge pull request #1369 from saper/nodl
e764b04 Merge pull request #1383 from mgreter/bugfix/memory-manager
73329f6 Merge pull request #1385 from mgreter/fix/mac-build
17f56ef Fix memory manager not tracking memory
bc8be92 Fix memory access bug (Fixes Mac CI builds)
7f2d973 Fix Makefile to create include directory on install
daeb86e Merge pull request #1380 from saper/emptysourcesContent
02aa085 Merge pull request #1379 from saper/tapmode
57f88e5 Don't emit sourcesContent if empty
78140ad Fix checking whether we can use TAP mode...
b0f37d0 move methods from directives to static functions
5e9437b No -ldl for FreeBSD
1f709b8 Fix error for multiplication of invalid units
````

So your work and current libsass diverged (this is normal in the process when more than one person works on the same code base).

What you need to do is to tell git to analyze what where your changes (diffs) to the original master back then (a61117a4) and try to re-apply them onto the current code base. You can do this step-by-step (to better understand the process maybe) or automatically via the `git rebase` command (that's why it is called "rebasing" - please rebase your changes).

Manual way:

````
git remote update
git checkout -b new-master origin/master
git log --oneline b3b564d ^new-master
(produces a list of changes you did)
git cherry-pick 2bf7801
<fix conflicts>
git cherry-pick 1b3f029
<fix conflicts>
....
````

and so on for all the changes listed.

The automated way is

````
git remote update
git checkout -b msvc-warnings b3b564d
git rebase origin/master
````

Because the code you have modified might have changed in the meantime too and more particularly because some of the code you have done has already been applied, you will run into the situation called "conflict".
`git` will stop and ask you to correct the files:

````
m> git checkout -B msvc-warnings b3b564d
m> git rebase origin/master
First, rewinding head to replay your work on top of it...
Applying: Fixing multiple MSVC compiler warnings and code analysis
Using index info to reconstruct a base tree...
M       src/ast.cpp
M       src/color_maps.cpp
M       src/eval.cpp
M       src/json.cpp
M       src/parser.cpp
<stdin>:64: trailing whitespace.

<stdin>:213: trailing whitespace.
    if (sources.size() == 0 && source_c_str) 
<stdin>:219: trailing whitespace.
                for (char* src : sources ) 
<stdin>:226: trailing whitespace.
                for (char* str : strings ) 
<stdin>:232: trailing whitespace.
    for (size_t m = 0; m < import_stack.size(); ++m) 
warning: squelched 3 whitespace errors
warning: 8 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging src/parser.cpp
Auto-merging src/json.cpp
Auto-merging src/eval.cpp
Auto-merging src/color_maps.cpp
CONFLICT (content): Merge conflict in src/color_maps.cpp
Auto-merging src/ast.cpp
CONFLICT (content): Merge conflict in src/ast.cpp
Failed to merge in the changes.
Patch failed at 0001 Fixing multiple MSVC compiler warnings and code analysis
The copy of the patch that failed is found in:
   /home/saper/sw/libsass/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
````

If you say `git status` it will show which files are the problem now:

````
m> git status

````rebase in progress; onto b3b564d
You are currently rebasing branch 'msvc-warnings' on 'b3b564d'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   src/color_maps.hpp
        modified:   win/libsass.vcxproj

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   src/ast.cpp
        both modified:   src/color_maps.cpp
````

So you need to edit `src/ast.cpp` and `src/color_maps.cpp`, searching for lines looking like this:

````
<<<<<<< HEAD
      int numval = (int)(r * 0x10000 + g * 0x100 + b);
=======
      double numval = r * 0x10000 + g * 0x100 + b;
>>>>>>> Fix a few MSVC warnings
````

This means that the bottom line comes from your change, and the above comes from the code that has changed (`HEAD` means current libsass master in this context).

You have to decide which line is correct and delete the `<<<<`, `===`, `>>>>` markings. 

Watch out as there may be many situations like this is the one file. After you are done, you save the file
and do

    git add src/ast.cpp

After all conflicting files are corrected, do `git rebase --continue`, and finally you will be done.

The push your changes to github using `-f` option:

    git push -f <your-github-remote> HEAD:master

**Comment by driekus77** [comment]
Hi all,

Thanks for the extensive help!

I managed somehow, with also a little help from SourceTree tool (Atlassian), to rebase in a code_issue branch and merge this branch back to master.
I now get:
"This branch is 18 commits ahead of sass:master"

Which looks a little bit strange because I didn't do 18 commits. Maybe something went wrong?

I have the code still save on my laptop (At work now).

Thanks again and greetings,

Henry

**Comment by saper** [comment]
You can check your commits ahead of master with `git log HEAD ^origin/master`

**Comment by xzyfer** [comment]
Hmm ok looks like things got a little messed up here. I've created https://github.com/sass/libsass/pull/1408 to track this from now on. This will allow me to fix the git history myself whilst maintaining @driekus77 authorship!

**Comment by driekus77** [comment]
Sorry for the mess-up and thanks for cleaning.
I should dive into git’s rebase a little further.

Just take the new PR and do with it what you want. I’ll take my hands off of it because You guys know the code the best. 
If I can help in any other way just mail me(e.g. testing).

Thanks again and Kind regards,

Henry

**Comment by xzyfer** [comment]
@driekus77 a couple rules of thumb when contributing PRs.

- Never PR from your forks master. Always create a new branch
- Never merge in the upstream master. Always rebase.

It's good practice to add the upstream repo as a git remote when you fork

```
$ git remote add upstream https://github.com/sass/libsass.git
```

Before creating a branch, sync your master with the upstream master.

```
$ git fetch upstream
$ git merge upstream/master
$ git push
```

Create your branch

```
git checkout -b my-branch
```

Track your branch

```
git push -u origin my-branch
```

Now work on your branch. When you're ready to PR make sure all your work is pushed

```
git push
```
****
Sometimes changes will happen on the upstream master whilst you've been be working on your branch. In this case you'll sometimes be asked to "rebase your branch off master". You can do so by syncing your fork's master with the upstream as described above.

```
$ git checkout master
$ git fetch upstream
$ git merge upstream/master
$ git push
```

Then rebasing your branch off your updated master

```
$ git checkout my-branch
$ git rebase
```

This is sometimes result conflicts during the rebase process. Once they are resolved you'll need to force push you branch since you've now rewritten the previous commits.

```
$ git push -f
```

Be very careful when force pushing. There is no undo.

**Comment by QuLogic** [comment]
> Never merge in the upstream master. Always rebase.

Depends on the project though. If you've already opened a PR, some prefer waiting until you're completely finished.

> Be very careful when force pushing. There is no undo.

That's when it's time to learn about [`git reflog`](https://git-scm.com/docs/git-reflog). (But in all seriousness, it's probably easier to create a temporary branch at the original point if you're at all worried in the slightest.)

**Comment by xzyfer** [comment]
@QuLogic sure force pushing can be recovered from. These are just general rules.

I'll almost never merge a PR that contains a merge commit. It's hell on git forensics in the future.

**Pull request closed without merging**
