### PR TITLE
Implement selector contextualization for keyframe rules

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/947

### CODE REVIEW

**Comment by am11** [comment]
:+1: :tada:

**Comment by xzyfer** [comment]
I don't think this is correct. `@keyframes` do not have selectors, they have a value/label that is a string. 

We should just resolve the interpolate value.

**Comment by am11** [comment]
@xzyfer, nice catch. But the *keyframes-selector* can be `from` and `to` as well? Would it make sense to keep a whitelist to qualify for the *keyframes-selector* (in case CSS brings more terms to the mix in future)? `["{numeric_value}%", "from", "to"]`
Ref: http://www.w3schools.com/cssref/css3_pr_animation-keyframes.asp

**Comment by mechanicalduck** [comment]
Specs: https://github.com/sass/sass-spec/pull/279

**Comment by mgreter** [comment]
@xzyfer seems odd, since IMO the only place where this value is set is in `Expand(Ruleset*)`:
```
Statement* Expand::operator()(Ruleset* r) {
...
  Keyframe_Rule* k = new (ctx.mem) Keyframe_Rule ...
  k->selector(r->selector()->perform(contextualize->with(0, env, backtrace)))
```

So the initial value seems to be a ruleset selector? But maybe you're right. It just looked like an oversight to me, and I thought that this would actually always be a selector ...

**Comment by xzyfer** [comment]
@mgreter it's because the parse is rather dumb about keyframes. It's on my todo list to improve.

@am11 I'd rather not for now because there's a lot of combinators to account for and it may change in the future.

**Comment by mgreter** [comment]
@xzyfer What do you think about this PR in the meantime? Just wonder if it's better than nothing, regarding that it doesn't seem to break any existing spec tests? Or should I close it then?

**Comment by xzyfer** [comment]
@mgreter I say leave for now. I'll take a pass doing naive interpolation expanding. If it works as expected I'll use that otherwise I'll ship this.

**Comment by xzyfer** [comment]
I'll take a look at this over the weekend. I think it's rather straight forward.

**Comment by mgreter** [comment]
@xzyfer do you think you can come up with a better solution in a reasonable timeframe for the 3.2.0 release? IMO I'd rather include this PR as is than not including a fix for the reported issue. Would really like to include this fix in the next beta! Or do you see any obvious regressions from this?

**Comment by mgreter** [comment]
Merged it beside the concerns given by @xzyfer. IMO this seems to be an improvement and we can add a more precise implementation later. Just want to have this included in the next release!

**Pull request merged**
