### PR TITLE
Work around C++11 nullptr

### PR DESCRIPTION
**Pull request by saper**
Provide CXX11_NULLPTR autoconf macro

### CODE REVIEW

**Comment by xzyfer** [comment]
@saper is this still relevant? If so please rebase off master.

**Comment by xzyfer** [comment]
Ping ^

**Comment by saper** [comment]
Rebased for @drewwells for experiments with limited compiler environment (Android, MacOS X 10.6 SDK, etc.)

**Comment by mgreter** [comment]
IMO it's easier to just replace `nullptr` with `0`, I see no real need for it, we use `0` all over the place.

**Comment by xzyfer** [comment]
I think agree with @mgreter. We don't have the issues `nullptr` is intended to fix.

**Comment by saper** [comment]
> I think agree with @mgreter. We don't have the issues `nullptr` is intended to fix.

Let's use at least NULL instead :)

**Comment by xzyfer** [comment]
Tracking in https://github.com/sass/libsass/issues/1657

**Pull request closed without merging**
