### PR TITLE
Refactor for `sass_op` export on C-API

### PR DESCRIPTION
**Pull request by mgreter**
This pulls out all the safe bits from my latest refactoring state. There are some duplicated code points (like converting values between C and C++). For now the main goal was to have sass ops exposed to the C-API. We also expose a function to stringify any sass value. To check if a value is truthy, you currently have to use an `or` call like `sass_op(OR, value, FALSE)`.

### CODE REVIEW

**Comment by saper** [comment]
@mgreter can you help me to figure out why `AM_PROG_AR` fails on your mingw32 setup?

**Comment by mgreter** [comment]
@saper can we move that discussion to https://github.com/sass/libsass/pull/1330, thx!

**Comment by mgreter** [comment]
If have split the first part of this PR into 3 different PRs: https://github.com/sass/libsass/pull/1346, https://github.com/sass/libsass/pull/1345 and https://github.com/sass/libsass/pull/1342. I hope they are sliced ok and have a good size to give it a proper review (//CC @xzyfer). They should all be uncritical since they do not really change any code logic. Will split out more PRs once they are merged!

**Comment by mgreter** [comment]
Next PRs pulled out from here: https://github.com/sass/libsass/pull/1348, https://github.com/sass/libsass/pull/1347 and still https://github.com/sass/libsass/pull/1342 (//CC @xzyfer)

**Pull request merged**
