### PR TITLE
Clean up C++ namespaces

### PR DESCRIPTION
**Pull request by saper**
This is to avoid problems with symbols that
may be defined by the compiler and conflict
with libsass.

- Never ever try 'using namespace std'
- Do not import namespaces with 'using namespace'
  or symbols in the headers - change propagate
  to all files including them

For .cpp files:

- Apply std:: where necessary, in case of many
  instances use 'using std::string' etc.

Fixes: #1308

### CODE REVIEW

**Comment by drewwells** [comment]
This is awesome!

**Comment by am11** [comment]
:+1: 

@spaer, have you tried compiling on i386 (via VM?) or SPARC? I am just curious if libsass is RISC-compatible in general.. <br/>(so my toaster can compile Sass natively :stuck_out_tongue_winking_eye:)

**Comment by saper** [comment]
There is no reason SPARC wouldn't work. I have access to an old SPARC machine to test but first I need a decent C++11 compiler there, will not be easy.

**Comment by xzyfer** [comment]
Currently blocked on #1249

**Comment by saper** [comment]
Will work on rebasing this as the refactoring goes in. Most important changes are in the headers, we can apply this in two stages - headers first and removal of `use namespace std;` in the .cpp files later.

**Comment by saper** [comment]
This is now rebased on top of d94ca1f

**Comment by saper** [comment]
Ouch, AppVeyor can't fetch MinGW at the moment :(

**Comment by drewwells** [comment]
SourceForge probably down upgrading mingw32 zip files with new spyware :-1:

**Comment by saper** [comment]
@drewwells who cares it's appveyor to be infected ;)

**Comment by xzyfer** [comment]
@saper did you want to rebase this now

**Comment by mgreter** [comment]
IMHO this should wait for https://github.com/sass/libsass/pull/1338

**Comment by saper** [comment]
This is a cleaned-up, simplified and rebased version of my previous patches.

**Comment by xzyfer** [comment]
Sorry for the delay here @saper. This seems perfectly reasonable to me. I'll :ship: this once the conflicts have been addressed.

**Comment by saper** [comment]
:rocket:

**Comment by xzyfer** [comment]
:boom:

**Comment by saper** [comment]
:rotating_light:

**Comment by xzyfer** [comment]
^^ I find this alarming

**Pull request merged**
