### PR TITLE
Relax parsing rules for type selector to start with number

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/2023

### CODE REVIEW

**Comment by xzyfer** [comment]
Please add test

**Comment by mgreter** [comment]
Issue is marked accordingly, will do them all in a batch later

**Comment by mgreter** [comment]
@xzyfer by the way how are new spec tests supposed to be added with the new spec test structure? I just saw that we now have multiple folders for `libsass-closed-issues`? //CC @chriseppstein

**Comment by xzyfer** [comment]
My understanding is that we've gone back to one input and the output for the nested syntax. The other libsass-closed-issues folders are for different output styles which are treated separately.

**Comment by mgreter** [comment]
That's how I handled it for the missing spec tests (there are still some open with closed issues, but I should have covered all the simpler once).

**Pull request merged**
