### PR TITLE
[WIP] Early preview of dart-sass parser backport

### PR DESCRIPTION
**Pull request by mgreter**
Needs https://github.com/sass/sass-spec/pull/1425

Please don't review, only leaving this here since I don't know when I'll have time to finish this up.
My vacations are over soon, so I don't know when I'll get around to complete this.
It's already semi usable, passing 80% of current spec tests.
Tried to preserve current libsass behavior, but
probably needs changes in eval stage too!
All the debug glory is still in the code!

Edit: I started to bring back some stuff to master in order to make this change a little bit smaller.
I also tagged all [open issues that should be fixed by this backport/refactoring][1] (ATM 76/120).

[1]: https://github.com/sass/libsass/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Dart+Backport+Done%22+

### CODE REVIEW

**Comment by mgreter** [comment]
Current state: 26 specs with (mostly minor) regressions, 122 newly passing

**Comment by mgreter** [comment]
Current state: all specs passing with around 150 newly passing

Ported scss, sass and css parser.
Lot of stuff still to do; most obvious:
- ParserStates for sourcemaps
- And correct error reporting
- Cleanup of import classes

**Comment by mgreter** [comment]
Current state: 3906 runs, 0 assertions, 0 failures, 0 errors, 752 skips

**Comment by xzyfer** [comment]
What do you see as the next step to getting this landed?

**Comment by mgreter** [comment]
@xzyfer Don't expect anything to land before winter.
I guess this should land for a 3.8 version (close to sass 4.0).

**Comment by mgreter** [comment]
Current state: 3906 runs, 0 assertions, 0 failures, 0 errors, 204 skips

**Comment by mgreter** [comment]
Current state: 3906 runs, 0 assertions, 0 failures, 0 errors, 178 skips, all CI passing

**Comment by mgreter** [comment]
Current state: 3906 runs, 0 assertions, 0 failures, 0 errors, 147 skips.
- Removed deprecated color arithmetic
- Removed quoted/constant string ambiguity
- Removed overly complex binary op eval stuff.

**Comment by mgreter** [comment]
An update to the preview, hope it's not too much swearing in the log. Just checking CI.

**Comment by mgreter** [comment]
Fixed the HRX files so we should at least get a result now (expecting a few memory leaks)

**Comment by mgreter** [comment]
Current stats: 4116 runs, 0 assertions, 13 failures, 0 errors, 168 skips
7 Failures are from the new superselector tests (which we didn't pass before anyway).
The rest are diffs in error messages (mostly from recursive/cylcic includes).
With the new spec we should be able to test the full call stack instead of only the first line.

**Comment by mgreter** [comment]
Current stats: 4143 runs, 0 assertions, 0 failures, 0 errors, 148 skips

**Comment by mgreter** [comment]
Current stats: 5814 runs, 0 assertions, 0 failures, 0 errors, 1196 skips
Lots of new spec tests, mostly failing regarding `@use`, `@forward` and new math module.

**Comment by mgreter** [comment]
Took long enough, but will now try to go for a LibSass 4.0 alpha release.
Still want to discuss the C-API, it already has been simplified internally.
Once I get CI stable here I will open a new PR for getting that ready.
I hope to have a 4.0 beta out by start to middle 2021.

@xzyfer I hope no objections from you to move this forward?
Since I pretty much rewrote everything, a PR review seems impossible!
But I guess since we're officially deprecated, we have more leeway!?
Alternatively I could publish everything within my own forks?

**Comment by xzyfer** [comment]
:ship: agree the deprecation means there are no expectations on the state of master.

**Comment by mgreter** [comment]
Continued in https://github.com/sass/libsass/pull/3135

**Pull request closed without merging**
