### PR TITLE
[WIP] Selector functions

### PR DESCRIPTION
**Pull request by onedayitwillmake**
**Please note: The code in this pull request was written by myself, and is does not represent my employer.** 

*updated 4/2/15*

I have 7 of the 8 built, I started from the bottom for some reason.
Bold means they are in and passing the test. 

I'm still actively working on this - however being my second PR and new to the library I wanted to make sure anyone could catch any silly things I was doing.

selector-nest($selectors...)
**selector-append($selectors...)**
**selector-extend($selector, $extendee, $extender)**
**selector-replace($selector, $original, $replacement)**
**selector-parse($selector)**
**simple-selectors($selector)**
**is-superselector($super, $sub)**
**selector-unify($selector1, $selector2)**

Some notes:
* Added stub functions
* Passing 'Contextualize' to `Native_Function signature in BUILT_IN(name) Expression*
* Added `ARGSELL` to compliment `ARG`, `ARGR`, `ARGM` since all the selector functions rely on that so heavily 
* Had to do some hairy things to get `Selector_List::selector_unify` and `Selector_List::selector_unify` to work
* Added `public static` methods version of Extend's subweave, *for now* I named it StaticSubweave just to make sure I don't step on any toes, will remove floating one if that seems fine to everyone
* Added a naiveTrim function to Node that removes any duplicate selectors (this is for `Complex_Selector::unify_with` was returning correct results but the final shared selector would sometimes appear twice, and blindly adding everything else in the collection (I could not get node's existing `trim` implementation to work - I Also could not find any references to it be used.
* Added a `public static` version of Extend's extendSelectorList
* Added param `isReplace` to `Extend::extendSelectorList` - which does not add the Selector if an extension takes place. 

Updated 04/02/15

### CODE REVIEW

**Comment by onedayitwillmake** [comment]
@mgreter @xzyfer I'm implementing `selector-replace`, and I'm trying to use extendSelectorList to do it - as I see that is how the ruby version is structured.

For example with such a test input:
```
selector-replace('.foo', '.foo', '.bar');  // should output .bar
``` 
I created a `populate_extends` method on `Selector_List` which takes another `Selector_List`, and appears to fill the entries with the correct value (in this case `.bar` for the key `.foo`). I naively attempted to pass that plainly into `Extend::extendSelectorList` but its outputs is `.foo`

I know that seems a bit dense, but here is some of the output. 

You can see that it picks up the `.bar` key for `.foo`, but right away it is dropped:
```
---------------------



selector_replace


---------------------



Subset_Map<K, V>::put key=.foo 
Subset_Map<K, V>::get key=& 
Subset_Map<K, V>::get key=.foo 
EXTEND COMPLEX: [.foo]
LOOP: .foo
EXTEND COMPOUND: .foo
Subset_Map<K, V>::get key=.foo 
SEQ: [&, .foo]
SELS: .bar
MEMBERS: .foo
SELF_WO_SEL: .foo
LHS: .foo
RHS: .foo
UNIFIED: .foo
SOURCES SETTING ON NEW SEQ: [.foo]
SOURCES NEW SEQ BEGIN: SourcesSet[]
SOURCES THIS EXTEND: SourcesSet[]
SOURCES WITH NEW SOURCE: SourcesSet[[.foo]]
SOURCES ON NEW SELECTOR AFTER ADD: SourcesSet[[.foo]]
SOURCES THIS EXTEND WHICH SHOULD BE SAME STILL: SourcesSet[]
RECURSING DO EXTEND: [.foo]
EXTEND COMPLEX: [.foo]
LOOP: .foo
EXTEND COMPOUND: .foo
Subset_Map<K, V>::get key=.foo 
SEQ: [&, .foo]
SELS: .bar
MEMBERS: .foo
SELF_WO_SEL: .foo
LHS: .foo
RHS: .foo
UNIFIED: .foo
SOURCES SETTING ON NEW SEQ: [.foo]
SOURCES NEW SEQ BEGIN: SourcesSet[]
SOURCES THIS EXTEND: SourcesSet[[.foo]]
SOURCES WITH NEW SOURCE: SourcesSet[[.foo]]
SOURCES ON NEW SELECTOR AFTER ADD: SourcesSet[[.foo]]
SOURCES THIS EXTEND WHICH SHOULD BE SAME STILL: SourcesSet[[.foo]]
EXTEND COMPOUND END: .foo
EXTENDED: []
CHOICES UNSHIFTED: [[.foo]]
EXTENDED NOT EXPANDED: [[[.foo]]]
PATHS: [[[.foo]]]
WEAVE: [[.foo]]
CURRENT: [.foo]
CURRENT POST POP: []
LAST CURRENT: [.foo]
SUB: [[]]
WEAVES: [[[.foo]]]







TRIM: [[[.foo]]]
RESULT INITIAL: [[[.foo]]]
SEQS1: [[.foo]] 0
TRIMASDF SEQ1: [.foo]
TRIMASDF SOURCES: SourcesSet[[.foo]]
MAX SPECIFICITY: 1000
SEQS1: [[.foo]]
SEQS2: [[.foo]]
CONTINUE
PUSHING: [.foo]
RESULT BEFORE ASSIGN: [[[.foo]]]
TEMP RESULT  0 [[.foo]]
RESULT: [[[.foo]]]
FINAL RESULT: [[[.foo]]]
TRIMMED: [[[.foo]]]
>>>>> EXTENDED: [[.foo]]
EXTEND COMPLEX END: [.foo]
RECURSING DO EXTEND RETURN: [[.foo]]
EXTEND COMPOUND END: .foo
EXTENDED: [[.foo]]
CHOICES UNSHIFTED: [[.foo], [.foo]]
EXTENDED NOT EXPANDED: [[[.foo], [.foo]]]
PATHS: [[[.foo]], [[.foo]]]
WEAVE: [[.foo]]
CURRENT: [.foo]
CURRENT POST POP: []
LAST CURRENT: [.foo]
SUB: [[]]
WEAVE: [[.foo]]
CURRENT: [.foo]
CURRENT POST POP: []
LAST CURRENT: [.foo]
SUB: [[]]
WEAVES: [[[.foo]], [[.foo]]]







TRIM: [[[.foo]], [[.foo]]]
RESULT INITIAL: [[[.foo]], [[.foo]]]
SEQS1: [[.foo]] 0
TRIMASDF SEQ1: [.foo]
TRIMASDF SOURCES: SourcesSet[]
MAX SPECIFICITY: 0
SEQS1: [[.foo]]
SEQS2: [[.foo]]
CONTINUE
SEQS1: [[.foo]]
SEQS2: [[.foo]]
SEQ2 SPEC: 1000
IS SPEC: 1000 >= 0 true
IS SUPER: true
FOUND MORE SPECIFIC
RESULT BEFORE ASSIGN: [[[.foo]], [[.foo]]]
TEMP RESULT  0 []
RESULT: [[], [[.foo]]]
SEQS1: [[.foo]] 1
TRIMASDF SEQ1: [.foo]
TRIMASDF SOURCES: SourcesSet[[.foo]]
MAX SPECIFICITY: 1000
SEQS1: [[.foo]]
SEQS2: []
SEQS1: [[.foo]]
SEQS2: [[.foo]]
CONTINUE
PUSHING: [.foo]
RESULT BEFORE ASSIGN: [[], [[.foo]]]
TEMP RESULT  1 [[.foo]]
RESULT: [[], [[.foo]]]
FINAL RESULT: [[], [[.foo]]]
TRIMMED: [[], [[.foo]]]
>>>>> EXTENDED: [[.foo]]
EXTEND COMPLEX END: [.foo]
extendedSelectors: [[.foo]]
	childNode: [.foo]



---------------------



DONE


---------------------



.test {
  a: .foo; }
```

Any insight is appreciated! Hoping to tackle this before the end of the week

**Comment by onedayitwillmake** [comment]
I actually made some progress, will have to post tomorrow - but im very close!

**Comment by mgreter** [comment]
@onedayitwillmake I have fixed a bug in #1033 regarding `is_superselector_of` function. Maybe you could verify if that fix works correctly with your WIP?

**Comment by onedayitwillmake** [comment]
@mgreter Sure thing, will write a function based version of the test case and post to spec

**Comment by onedayitwillmake** [comment]
@mgreter i can't see the details of why the appveyer builds are failing. Normally there is a link, could you point me in the right direction?

**Comment by xzyfer** [comment]
@onedayitwillmake the build is failing because the branch in unmergable. Rebase of the lastest sass/libsass#master and it should work. 

Please **do not** merge master into your branch, it messes up the git history and makes git forensics nearly impossible.

**Comment by xzyfer** [comment]
Superseded by https://github.com/sass/libsass/pull/1064

**Pull request closed without merging**
