### PR TITLE
Simplify autotools build

### PR DESCRIPTION
**Pull request by mgreter**
- Generate sass_version.h
- Use $(EXEEXT) for executables
- No need for -lm and C++ library.
- They should be provided by libtool.

Work done by @saper !

### CODE REVIEW

**Comment by saper** [comment]
Can we also have `AM_PROG_AR` on mingw32? Otherwise autoreconf complains out:

````
/usr/local/share/automake-1.15/am/ltlibrary.am: warning: 'libsass.la': linking libtool libraries using a non-POSIX
/usr/local/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
Makefile.am:28:   while processing Libtool library 'libsass.la'
```

**Comment by saper** [comment]
Looks like [_AC_PROG_CC_G](http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob;f=lib/autoconf/c.m4;h=4c87d2121ad03b06e19115dfd6b6eb7684bbbd06;hb=HEAD#l504) autoconf test sets `-O2 -g` as the default compiler flags on gcc-likes (including clang).

**Comment by drewwells** [comment]
just as a sanity check, b/c this has been changing a lot lately. Here's the params I pass to build libsass

    -lsass -lsdc++ -lm -ldl -std=c++11

lm is removed by this PR and I think ldl was removed in another. Which of these params should I be passing now?

**Comment by saper** [comment]
Can you try running `autoreconf` and then `./configure` ? libtool should find them

**Pull request merged**
