### PR TITLE
Fix sizeof argument

### PR DESCRIPTION
**Pull request by unmole**

### CODE REVIEW

**Comment by saper** [comment]
Wouldn't `sizeof(union Sass_Value *)` work as well?

**Comment by unmole** [comment]
@saper It would. The `void*` just makes it really obvious that you only need enough memory to store a pointer.

**Comment by xzyfer** [comment]
Thanks @unmole. I'm happy with either approach.

**Comment by mgreter** [comment]
I cherry picked this in https://github.com/sass/libsass/pull/1609. Thanks for your contribution @unmole!

**Pull request closed without merging**
