### PR TITLE
Use GNUmakefile.am not to conflict with static Makefile

### PR DESCRIPTION
**Pull request by saper**

### CODE REVIEW

**Comment by QuLogic** [comment]
Good idea. Unintentionally dirty workspaces are very annoying with git.

**Comment by xzyfer** [comment]
LGTM. @mgreter you've been playing with the build stuff lately, any thoughts here?

**Comment by xzyfer** [comment]
I've read the conversation in https://github.com/sass/libsass/pull/1352. :ship: this. Thanks @saper.

**Comment by saper** [comment]
So, `sass_version.h` is the next one to deal with :)

**Pull request merged**
