### PR TITLE
Implement third party plugin loader

### PR DESCRIPTION
**Pull request by mgreter**
This is a first working draft to address #878
Also added an [example plugin] [1] to this branch!

libsass-plugins-2

Build currently fails because of sassc: https://github.com/sass/sassc/pull/98

[1]: https://github.com/mgreter/libsass/blob/feature/plugin-functions/plugin.cpp

### CODE REVIEW

**Comment by mgreter** [comment]
IMHO this is ready to be merged since it compiles fine in all CI build!
I would like to mark this feature as experimental and include it in 3.2!

**Comment by xzyfer** [comment]
I think you should move the example plugin out of root i.e. `/examples/plugin/basic.cpp`

Otherwise :+1:

**Comment by mgreter** [comment]
Actually I intended to remove it before I remove the WIP tag ...

**Comment by xzyfer** [comment]
That'll work also

**Comment by mgreter** [comment]
I've removed the sample files. Will add the code to the wiki once this is merged!

**Comment by xzyfer** [comment]
Awesome work @mgreter

**Comment by lunelson** [comment]
This is a super exciting feature if it does what I think. Would this be a means to add advanced math functions, for example?

Example plugin link above is 404.

**Comment by mgreter** [comment]
Yep, you could create a dll with various custom (math) functions to be loaded by libsass.

**Pull request merged**
