### PR TITLE
Include <cstdint> unconditionally

### PR DESCRIPTION
**Pull request by saper**
A follow up to #1721

### CODE REVIEW

**Comment by saper** [comment]
Not sure what PR ready means ... but hey, green looks so much better!

**Comment by mgreter** [comment]
It's mostly just usefull for issues, but I tend to flag PRs that I feel can be "blindly" merged if needed. Just a minor nitpick, a comment in the source for such conditionals would be usefull. Other than that :+1:

**Comment by xzyfer** [comment]
I'm all for this. We've talked bout VS2013 before. The only reason we haven't addressed it yet is that we don't have a plan for testing it in parallel with VS2015.

https://github.com/sass/libsass/pull/1719#issue-116363736

**Comment by saper** [comment]
This change removes VS version conditional - we should always include this header because we use width int types. I tested it with VS2013 and VS2015 was tested by appveyor.

We should be able to run tests for VS2015 as an additional environment if we want.

**Comment by xzyfer** [comment]
Rebuilding. If CI is still happy :ship:

**Pull request merged**
