### PR TITLE
Do not use `0` for initializing SharedImpl

### PR DESCRIPTION
**Pull request by glebm**
This is more readable and avoids creating a temporary `SharedImpl(nullptr)`

Later on this will allow us to initialized `SharedImpl` directly from `T*`, avoiding a redundant temporary `SharedImpl` construction and counter increment+decrement.

Also changes `is_superselector_of` signature to accept a const pointer, avoiding an unnecessary `SharedImpl` there.

ASAN passes locally.

### CODE REVIEW

**Comment by xzyfer** [comment]
I can confirm with this the `ASAN` are now gone :tada:

However it does appear that somewhere along the way some test regressions have crept in.

**Comment by xzyfer** [comment]
I'm kicking off a master build to see if the test failures are present there. https://travis-ci.org/sass/libsass/builds/457712914

**Comment by glebm** [comment]
The ASAN build on Travis is not fixed yet but I'm looking into it.

**Comment by xzyfer** [comment]
Master is failing on the same tests so let's keep moving this forward

**Pull request merged**
