### PR TITLE
Coverity scan

### PR DESCRIPTION
**Pull request by nschonni**
First test of the setup.
Currently failing on my Travis, but that might be because it's looking for the right repo https://travis-ci.org/nschonni/libsass/jobs/201763546#L387
Alternately the secure string is generated incorrectly.

### CODE REVIEW

**Comment by nschonni** [comment]
@xzyfer I think you'll need to merge this to see if it actually works since i'm not seeing the addon appearing in the PR config payload https://travis-ci.org/sass/libsass/jobs/201764378/config

**Comment by xzyfer** [comment]
Travis secrets won't work for PRs from forked repos. It's a security feature.

**Comment by nschonni** [comment]
True about the secrets, but i think the addon might also just be ignored for PRs since it doesn't show up in the config.

**Comment by xzyfer** [comment]
I found a hacky way to make you a contributor. Use your powers for good.

**Comment by nschonni** [comment]
Looks like it really wants an email https://travis-ci.org/sass/libsass/jobs/201768367#L390
I'll try mine for now, and just use a dummy in the end

**Comment by mgreter** [comment]
Thanks @nschonni for this. It actually pointed out more than I expected! I looked through the list and it catched 2 memory leaks (due to the new memory handling) and one possible out of bound access. The rest were mostly undefined behaviors due to possibly unitialized values. Most of them were unproblematic with the given behavior of gcc/clang/msvc. None the less I fixed most of them with #2335. The rest seem to be false positives, but I have to see the updated report after said PR is merged (I pushed these changes also to the coverity branch). The rest was mostly cosmetic (i.e. "logical dead code")!

**Pull request merged**
