### PR TITLE
Refactor contextualize into eval [WIP]

### PR DESCRIPTION
**Pull request by mgreter**
Remove contextualize and contextualize_eval by placing the functionallity into eval. Also refactors usage of Parent_Selector and gets rid of Selector_Reference. We now pretty much only store state on the expander itself (selector_stack, env_stack, etc). First iteration that should not break CI.

### CODE REVIEW

**Comment by xzyfer** [comment]
Needs a clean up but generally speaking it looks sane

**Comment by xzyfer** [comment]
Does your parent selector refactor help with https://github.com/sass/libsass/issues/1210 by any chance?

**Comment by mgreter** [comment]
Well, it should help to make more sense out of the actual code. I actually did not understand why it was doing what it was doing. So yes, it could help with that, since it is more obvious where and which parent selector we are referring to IMHO. But it really depends on the underlying problem :)

**Comment by mgreter** [comment]
Took a look at your linked issue and I guess I know how we can fix it. IMHO we need another selector type beside `Parent_Selector`, namely `Root_Selector`. Currently I thought I could just use NULL to represent that, but this would need quite some refactoring, since we have a lot of places where we would need to check for that potential NULL pointer. Parent selectors now only "live" in the selector_stack, so you can more easily tamper with it. I used this technique to implement Parent_Selector rendering (pop one selector off the stack, render recursively and push it back once finished). So in theory we just should need to add a `Root_Selector` to that stack when rendering/expanding root nodes. At least that's what I would guess. I'm currently focusing in another area, which will take quite some time (values/nodes and memory management, plus some basic performance considerations; currently catching up with the latest tricks in mark and sweep GC implementations). So I have absolutely no ETA if/when I will come around to implement this, so I thought I document it here for future references.

**Comment by xzyfer** [comment]
Can this be applied without https://github.com/sass/libsass/pull/1249?

It looks like https://github.com/sass/libsass/pull/1249 does a bunch of this work as well.

**Pull request closed without merging**
