### PR TITLE
Implement missing error checks

### PR DESCRIPTION
**Pull request by mgreter**
Should pass specs https://github.com/sass/sass-spec/pull/680

- Fixes: https://github.com/sass/libsass/issues/1724
- Fixes https://github.com/sass/libsass/issues/1550
- Fixes https://github.com/sass/libsass/issues/871
- Fixes https://github.com/sass/libsass/issues/1670
- Fixes https://github.com/sass/libsass/issues/1653

One minor issue not on par with ruby sass, but that will change once we switch sass specs to 3.4.20.

### CODE REVIEW

**Comment by mgreter** [comment]
Will merge this as soon as ci is :green_heart: 

If any of these error checks regress we can still just uncomment them. I hope we have gathered enough specs to cover pretty much all cases, altough I'm not to sure about at root, media blocks etc. But it should also be quite easy to adjust the conditions, since we now can query the parent scope type in parser. I also added a few of my own spec tests to cover the main use cases I could come up.

**Comment by xzyfer** [comment]
Spec activated in https://github.com/sass/sass-spec/pull/684

**Comment by xzyfer** [comment]
Spec for #1675 activated in sass/sass-spec#685

**Comment by xzyfer** [comment]
Spec for #871 activated in sass/sass-spec#686

**Comment by xzyfer** [comment]
Remaining spec for #1653 activated in sass/sass-spec#687

**Comment by xzyfer** [comment]
Spec for #1550 activated in sass/sass-spec#688

**Pull request merged**
