### PR TITLE
Do not include css comments in static values

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/1568

### CODE REVIEW

**Comment by xzyfer** [comment]
:+1: 

Please avoid further changes to the lexers and parser. I have a WIP with heavy refactors for 3.3.1.

**Comment by xzyfer** [comment]
@mgreter I'm going to tag 3.3 stable when this is merged.

**Comment by xzyfer** [comment]
If getting this stable require more changes than this, I say leave it. This code has already been heavily refactored in my WIP branch.

**Comment by mgreter** [comment]
Just needed to restart appveyor. Can you wait until I've run my extended regression tests with perl-libsass (like memory leak tests etc). Will report back in a few ticks ...

**Comment by xzyfer** [comment]
Sure, just say when!

**Comment by mgreter** [comment]
OK, no memory leak found, plugins and custom functions seem to work :rocket: :roller_coaster:

**Comment by xzyfer** [comment]
Spec activated https://github.com/sass/sass-spec/pull/562

**Pull request merged**
