### PR TITLE
Fix `is_superselector_of` function

### PR DESCRIPTION
**Pull request by mgreter**
Fixes https://github.com/sass/libsass/issues/823

### CODE REVIEW

**Comment by mgreter** [comment]
@xzyfer should we include this in next 3.2.0-beta.5 release?

**Comment by xzyfer** [comment]
Maybe this is best left for when selector functions lands.

**Comment by mgreter** [comment]
I actually thought it would make sense to have it merged before selector functions, since it could possibly have an impact there (they may suffer from the same bug). So I thought it would be good to already have it merged. Otherwise chances are that this bug will be fixed twice !?

**Comment by xzyfer** [comment]
Cool, go for it. I just thought it might be a risky change but it seems fine

**Comment by mgreter** [comment]
Pinged @onedayitwillmake so he maybe can verify this changes to be sane. I guess he should have a few additional spec tests by now, so maybe he can test if this brakes any existing behavior.

**Comment by mgreter** [comment]
OK, just made some tests with the WIP branch and it seems alter results for the new selector function tests. So I will leave this open for now!

**Comment by mgreter** [comment]
OK, lets wait for selector-functions and the new spec tests which should cover this topic better.
IMO the selector functions cannot be merged without a proper superselector handling anyway!

**Comment by onedayitwillmake** [comment]
@mgreter I agree, i can merge that in. The selector function, is essentially parsing the selectors, returning the result of calling that method

**Comment by mgreter** [comment]
There is a very strange and IMO wrong logic at work with ruby sass and `is_superselector`. I fail too see why ruby sass produces different results for these two tests:

```css
test-a {
  // false
  $a: "a + c + d";
  $b: "a + b + c + d";
  a: is_superselector($a, $b);
}

test-b {
  // true
  $a: "a + c + d + e";
  $b: "a + b + c + d + e";
  a: is_superselector($a, $b);
}
```

IMO I found the code part in ruby sass that is mainly responsible for this behavior:

```ruby
# .foo > .baz is not a superselector of .foo > .bar > .baz or .foo >
# .bar .baz, despite the fact that .baz is a superselector of .bar >
# .baz and .bar .baz. Same goes for + and ~.
return if seq1.length == 3 && seq2.length > 3
```

With this info I might be able to re-produce the IMO faulty behavior ...

**Comment by mgreter** [comment]
This is included in my WIP branch for 3.3!

**Pull request closed without merging**
