### PR TITLE
Code hardening

### PR DESCRIPTION
**Pull request by mgreter**
Addresses +80% of the issues found by coverity.
I don't seem to be able to "restart" the checking though.

### CODE REVIEW

**Comment by xzyfer** [comment]
Build frequencies for coverity are restrictive - https://scan.coverity.com/faq#frequency

We discussed in https://github.com/sass/libsass/issues/2325 and in Slack that as a result we mostly use it in addition to my exisiting pre-release sanity check.

I think for now there's a `coverity_scan` branch that will execute a new build.

**Comment by xzyfer** [comment]
The CodeKit team is keen to get 3.5 into a release. I'm planning to tag 3.5.0.beta.3 with this and #2334 today to get them over the line and get #2330 into node-sass.

**Comment by mgreter** [comment]
Ran `leak-test.pl` for this branch and valgrind didn't report anything beside the segfault for issue 2307.

**Comment by xzyfer** [comment]
Nice one!

```
Please find the latest report on new defect(s) introduced to sass/libsass found with Coverity Scan.

1 new defect(s) introduced to sass/libsass found with Coverity Scan.
25 defect(s), reported by Coverity Scan earlier, were marked fixed in the recent build analyzed by Coverity Scan.

New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)
```

**Comment by bdkjones** [comment]
Stoked to see static analysis incorporated! It has saved me from shooting myself in my foot many, many times. Especially after refactoring stuff.

**Comment by xzyfer** [comment]
Kicked off another coverity scan. I'll tag 3.5.0.beta.3 pending the results of coverity and my release testing.

**Pull request merged**
