### PR TITLE
Remove `To_String` by using `AST->to_string` and `inspect`

### PR DESCRIPTION
**Pull request by mgreter**
This cleans up the usage of `perform(&to_string)` by only using inspect. Also adding additional `TO_SASS` output mode, since ruby sass has differences between `to_sass` and `inspect` and both are used in various places (i.e. error reporting). Now every `AST_Node` has a `to_string`, `to_sass` and `inspect` method, and all return a std::string. They all internaly use the `inspect` visitors, so we only need to implement all types only once for all variations in one place. With this I hope we can more easily match ruby sass and I already saw one or two things that need to be implemented for certain options. The `to_sass` mode specially is responsible to add parentheses were needed.

This is basically the continuation of https://github.com/sass/libsass/pull/1754

### CODE REVIEW

**Comment by mgreter** [comment]
@xzyfer I'm thinking about renaming `Inspect` visitor class to `Stringify`, because the name is IMO a bit confusing, since it handles all the stringification now. In terms of ruby sass it never did what ruby sass internaly does with `inspect`. We should use `to_string`, `to_sass` and `inspect` methods on `AST_Node` instances. These correspond to ruby sass `perform`, `#{node.to_sass(opts)}` and `#{node.inspect}`.

I also want to add an emitter that does not create a sourcemap, since for these methods it's not necesarry (but that's really just a performance optimization). Things start to come together.

**Comment by xzyfer** [comment]
@mgreter Ruby Sass calls it the [to_css](https://github.com/sass/sass/blob/stable/lib/sass/tree/visitors/to_css.rb) visitor. Seems like an ideal name to me?

**Comment by xzyfer** [comment]
>Now every AST_Node has a to_string, to_sass and inspect method, and all return a std::string. 

This is a great change. I wasn't expecting to implement this until 3.4. Nice work.

**Comment by saper** [comment]
I am getting this now:
> gmake BUILD=debug-shared CC=cc CXX=c++
mkdir lib
cc -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/cencode.o src/cencode.c
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/ast.o src/ast.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/base64vlq.o src/base64vlq.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/bind.o src/bind.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/color_maps.o src/color_maps.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/constants.o src/constants.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/context.o src/context.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/cssize.o src/cssize.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/emitter.o src/emitter.cpp
c++ -g -DDEBUG -DDEBUG_LVL="NONE" -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/environment.o src/environment.cpp
src/environment.cpp:183:38: error: no matching member function for call to 'to_string'
        { std::cerr << " : " << val->to_string(true, 5); }
                                ~~~~~^~~~~~~~~
src/ast.hpp:94:25: note: candidate function not viable: requires single argument 'opt', but 2 arguments were
      provided
    virtual std::string to_string(Sass_Inspect_Options opt) const;
                        ^
src/ast.hpp:95:25: note: candidate function not viable: requires 0 arguments, but 2 were provided
    virtual std::string to_string() const;
                        ^
1 error generated.
````

is it because of this change?
````

**Comment by xzyfer** [comment]
@saper is that error still happening on b6841ed? I'm unable to reproduce.

**Comment by saper** [comment]
Yes, see https://github.com/sass/libsass/issues/1917#issuecomment-196546027

**Pull request merged**
