### PR TITLE
Add missing implementation of sass_importer_set_list_entry.

### PR DESCRIPTION
**Pull request by tristanlins**
@drewwells already mentioned in https://github.com/sass/libsass/pull/1000#issuecomment-87499756 that the implementation of `sass_importer_set_list_entry` is still missing. I need this function for my jsass (a java libsass integration) library, so I simply implemented it. :-)

### CODE REVIEW

**Comment by drewwells** [comment]
works, awesome! :trophy:

**Comment by xzyfer** [comment]
Seems straight forward to me. @mgreter please take a look and pull the trigger.

**Comment by xzyfer** [comment]
Since you're here I see no reason not to also add the getter. Can you please do so?

**Comment by xzyfer** [comment]
bump @tristanlins

**Comment by tristanlins** [comment]
pong @xzyfer :-)

**Comment by xzyfer** [comment]
:heart_eyes:

**Pull request merged**
