### PR TITLE
Rename uchar_t to uchar32_t to avoid conflicts on SmartOS

### LINKED ISSUE #850: Compile fails on Joyent SmartOS
This compile error happens when attepmting to install via:  "npm install grunt-sass"

  CXX(target) Release/obj.target/binding/src/libsass/json.o
../src/libsass/json.cpp:159:18: error: conflicting declaration 'typedef uint32_t uchar_t'
In file included from /usr/include/sys/wait.h:38:0,
                 from /usr/include/stdlib.h:36,
                 from ../src/libsass/json.cpp:29:
/usr/include/sys/types.h:98:23: error: 'uchar_t' has a previous declaration as 'typedef unsigned char uchar_t'
../src/libsass/json.cpp: In function 'int utf8_write_char(uchar_t, char*)':
../src/libsass/json.cpp:299:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:299:3: warning: comparison is always false due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:299:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:305:25: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:310:25: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp: In function 'void to_surrogate_pair(uchar_t, uint16_t*, uint16_t*)':
../src/libsass/json.cpp:351:3: warning: comparison is always false due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp:351:3: warning: comparison is always true due to limited range of data type [-Wtype-limits]
../src/libsass/json.cpp: In function 'void emit_string(SB*, const char*)':
../src/libsass/json.cpp:1214:42: error: cannot convert 'uint32_t* {aka unsigned int*}' to 'uchar_t* {aka unsigned char*}' for argument '2' to 'int utf8_read_char(const char*, uchar_t*)'
make: *** [Release/obj.target/binding/src/libsass/json.o] Error 1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7931620-compile-fails-on-joyent-smartos?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Candid**
Fixes #850

### CODE REVIEW

**Comment by QuLogic** [comment]
Strictly speaking, the `_t` suffix is reserved in POSIX, so since you're changing it everywhere, best to remove it entirely.

**Comment by xzyfer** [comment]
Applying #1094 resolves this issue for some users - https://github.com/sass/node-sass/issues/858#issuecomment-92386749

I'm happy to ship this in 3.0.0

**Comment by Candid** [comment]
@xzyfer cool. Do you want me to remove `_t` suffix as @QuLogic suggested, so that the type name becomes `uchar32`? I thinks it's a good idea since `_t` is indeed reserved in POSIX. Alternatively, the entire `typedef` can be dropped and `uint32_t` can be used directly. `uchar32_t` is only used in json.cpp file, and `uint32_t` is used throughout the rest of the codebase, so this might be the best way to address the issue. I'll be happy to make the change, just let me know which way you want to go.

**Comment by saper** [comment]
Pushed #1099 to simply replace ucha_t with uint32_t (essentially it's @candid 's version)

**Comment by xzyfer** [comment]
@Candid please do  .
@saper your PR is currently failing out Windows CI, I've commented there.

**Comment by Candid** [comment]
@xzyfer not sure which way you wanted to go, but I went with using `uint32_t` directly and got rid of the alias. So this is essentially identical to @saper's PR (with the comments fixed so it passes on Windows).

**Comment by saper** [comment]
Coool, almost arrived on the same commit ID :)

**Comment by xzyfer** [comment]
Superseded by #1099. Thanks for you work @Candid !

**Comment by QuLogic** [comment]
@xzyfer Did you forget to close as well?

**Comment by xzyfer** [comment]
My bad, I thought I did.

**Pull request closed without merging**
