### PR TITLE
Update to use upcoming sass-spec refactor

### PR DESCRIPTION
**Pull request by chriseppstein**
This is not merge-ready, I want to test changes to the libsass build against my sass-spec branch in CI.

### CODE REVIEW

**Comment by xzyfer** [comment]
The test failures appear to be related to changes in whitespace/new line normalisation.
AppVeyor appear to be running sass-spec@master which is why it's passing. You'll need to update `appveyor.yml` to checkout your branch.

**Comment by xzyfer** [comment]
Interesting, AppVeyor failed sass-spec (invalid -V flag) but didn't fail the build. We'll need to look in to that separately.

**Comment by chriseppstein** [comment]
There was a bug in the new spec runner that caused tests that needed to be "cleaned" to not be. That and some tests with a todo in their name weren't marked as pending yet in the metadata. Once those were sorted out, all the specs appear to be passing now.

**Comment by chriseppstein** [comment]
merged as 10d82926d3683752bd64705ab93b4a812a2c7747

**Pull request closed without merging**
