### PR TITLE
Refactor/directive parsing

### LINKED ISSUE #1233: Block comments should be preserved in "static" at rules
When using @'s it appears to fail.

```scss                  
@-moz-keyframes animatetoptop /* Firefox */ line 429
{
from {width:0%}
to {width:100%}
}
```
I'll get the following error.
```
[16:36:40] gulp-notify: [Compile Error] stylesheets\apps\tmm\_results.scss
429:17  top-level directive must be terminated by ';'
```

I'm using gulp-sass: 2.0.1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/16485592-block-comments-should-be-preserved-in-static-at-rules?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mgreter**
Spec test https://github.com/sass/sass-spec/pull/764 (excerpt from https://github.com/sass/libsass/pull/1900, fixes #1233)

- libsass-todo-issues\issue_1233\expected.nested
- libsass-todo-tests\scss-tests\127_test_moz_document_interpolation\expected.nested
- libsass-todo-tests\libsass\moz-document\basic\expected.nested
- libsass-todo-tests\libsass\moz-document\interpolated\expected.nested

### CODE REVIEW

**Comment by xzyfer** [comment]
If you're going to make this massive of a change I suggest doing your best to move more inline with Ruby Sass implementation like with cssize.

The closer our internal data flow and logic is to Ruby the easier it's going to be keep features in sync, and prevent weird edge cases.

**Comment by mgreter** [comment]
If you check the commits this is exactly what is happening here!

**Comment by xzyfer** [comment]
I wasn't insinuating it wasn't what you were doing. I just wanted to make sure we were on the same page.

**Comment by mgreter** [comment]
Just assumed, because the main reason why this change is that massive is because it is following ruby sass closely in the first place :wink:

**Comment by mgreter** [comment]
Just to be clear, I agree to follow ruby sass closely when it comes to the parser and the internal ast in general. But we can (and should) do better in libsass with manipulation and processing. I guess ruby sass choose to do quite a few operations (I'm specially refering to extend) in a monolithic approach. This makes sense in a language with dynamic function dispatching, since adding to many method calls in tight loops (code hotspots) can lead to bad performance. We don't have this constraint in c++ and should embrace the possibility of micro functions for selector manipulations. Another reason for that is that writing big monolithic functions in C++ (or any strict types language for that matter) tends to get tiresome, specially when a lot of loops are involved. But so far extend works and I don't want to touch any of that directly ported `Node` class if possible. Which reminds me of https://github.com/sass/libsass/issues/1392 ...

**Comment by xzyfer** [comment]
I agree. I tend to avoid the extend code this exact reason.

**Comment by xzyfer** [comment]
You'll probably have to rebase your sass-spec branch of master.

**Pull request merged**
